import type { SupportPack } from '../../types/content';

/** Türkische Verständnishilfe. Nur sichtbar, wenn das Kind sie antippt. */
export const supportTr: SupportPack = {
  'a1-s1': { hint: '„Markieren" = işaretlemek. Uygun olan HER şeyi işaretlemelisin, sadece bir tanesini değil.', explanation: 'Toplam 3 elma var. „Markiere" dediğinde uygun olan hepsini işaretlersin.' },
  'a1-s2': { hint: 'Her hayvanın bacaklarını say. Kuşun 2, balığın 0 bacağı var.', explanation: 'Köpek, kedi ve atın dört bacağı var. Yani 3 hayvan.' },
  'a1-s3': { hint: '„Alle" = hepsi. Yani hiçbir daireyi atlamadan hepsini gösterirsin.', explanation: '„Markiere alle" = uygun olan her şeyi göster demektir.' },
  'a1-t': { hint: '10’dan küçük demek: sayarken 10’dan önce gelen sayılar. 12 ve 15 sonra gelir.', explanation: '4, 9 ve 7 sayarken 10’dan önce gelir, yani 10’dan küçüktür.' },
  'a2-s1': { hint: 'Her sıradaki yıldızları parmağınla sayarak kontrol et: 1, 2, 3, 4, 5.', explanation: 'Ortadaki sırada 5 yıldız var. „Wähle aus" dediğinde tek bir cevap seçersin.' },
  'a2-s2': { hint: 'Önce kedileri say (3), sonra köpekleri say (2). Bu iki sayının geçtiği cümleyi seç.', explanation: '3 kedi ve 2 köpek var. Cümledeki sayılar saydığın sayılarla aynı olmalı.' },
  'a2-s3': { hint: '6’dan büyük = sayarken 6’dan sonra gelen sayı. 7, 8, 9 gibi.', explanation: '8 sayarken 6’dan sonra gelir, bu yüzden 6’dan büyüktür.' },
  'a2-t': { hint: 'Hangi soruya „3" veya „7" diye cevap verirsin? „Wie viele" = kaç tane, sayı ister.', explanation: '„Wie viele …?" adet sorar, cevabı bir sayıdır.' },
  'a3-s1': { hint: 'Kendine sor: Bu yenir mi, yoksa binilir mi? Yeniyorsa Obst, biniliyorsa Fahrzeug.', explanation: 'Her resmin tam bir yeri var. „Zuordnen" = eşleştirmek.' },
  'a3-s2': { hint: 'Sayı doğrusunu düşün: 10’dan önce gelenler küçük, sonra gelenler büyük.', explanation: '4, 8 ve 2 → 10’dan önce. 13 ve 17 → 10’dan sonra.' },
  'a3-s3': { hint: '„Zuordnen" = her şeyi ait olduğu yere koymak. Hesap yapmazsın.', explanation: '„Ordne zu" = sınıflandır, her şeyi yerine koy.' },
  'a3-t': { hint: 'Canlı mı, yoksa onunla çalışılan bir alet mi?', explanation: 'Köpek ve kedi hayvan; çekiç ve pense alettir.' },
  'b1-s1': { hint: 'Baba 4 kurabiye ekliyor. Tam 4 kurabiyeyi masaya taşı.', explanation: '4 kurabiye, 5 kurabiyenin üzerine ekleniyor. Masadaki miktar artıyor.' },
  'b1-s2': { hint: 'Masadaki kurabiye sayısı arttı. Bir miktar artıyorsa toplama yaparsın: 5 + 4.', explanation: 'İki grup birleşiyor: 5 kurabiye ve 4 kurabiye. Bu yüzden 5 + 4.' },
  'b1-s3': { hint: '5’ten devam ederek say: 6, 7, 8, 9. Cevap 9.', explanation: '5 + 4 = 9. Masada şimdi 9 kurabiye var.' },
  'b1-t': { hint: 'Otobüse binmek = sayı artar. 7 + 6 hesapla.', explanation: '7 + 6 = 13. Çocuklar bindiği için otobüsteki grup büyüyor.' },
  'b2-s1': { hint: 'Sorunun son cümlesini oku: „Mina’nın kaç misketi kaldı?" Yani Mina’nın kalan sayısı aranıyor.', explanation: 'Aranan, Mina’da kalan miktar. Ne sorulduğunu bilmek hesabı kolaylaştırır.' },
  'b2-s2': { hint: 'Mina’dan Ben’e tam 3 misket taşı. Kalanlar Mina’da kalır.', explanation: 'Mina’nın 8 misketinden 3’ü gidiyor. Miktarı azalıyor.' },
  'b2-s3': { hint: 'Mina 8 ile başlıyor, 3 tanesini veriyor. Bir şey gidiyorsa çıkarma: 8 − 3.', explanation: '8’lik gruptan 3 çıkarılıyor: 8 − 3.' },
  'b2-s4': { hint: '8’den geriye say: 7, 6, 5. Mina’da 5 misket kalır.', explanation: '8 − 3 = 5. Mina’da 5 misket kalır.' },
  'b2-t': { hint: 'Yenen üzümler tabakta kalmaz. 12 − 4 = 8.', explanation: '12 − 4 = 8. Lea yediği için tabaktaki miktar azalır.' },
  'b3-s1': { hint: 'Lisa hediye ediyor, Tom alıyor. Yani Tom’un sayısı artıyor.', explanation: 'Tom sticker alıyor, miktarı artıyor.' },
  'b3-s2': { hint: 'Sara kart veriyor, elindeki azalıyor: 14 − 5.', explanation: 'Sara’nın 14 kartından 5’i gidiyor: 14 − 5.' },
  'b3-s3': { hint: '14’ten geriye say: 13, 12, 11, 10, 9. Cevap 9.', explanation: '14 − 5 = 9. Sara’da 9 kart kalır.' },
  'b3-t': { hint: 'Sepetten çıkarılan elmalar sepette kalmaz: 15 − 6 = 9.', explanation: '15 − 6 = 9. Sepette 9 elma kalır.' },
  'c1-s1': { hint: 'Eşleştir: bir balık – bir kaplumbağa. Artanlar hangi taraftaysa orası daha çok.', explanation: '6 > 4. Eşleştirdikten sonra 2 balık artıyor, yani balık daha fazla.' },
  'c1-s2': { hint: 'Her yıldıza bir kalp düşüyor mu? Hiçbir şey artmıyorsa sayılar eşittir.', explanation: '5 ve 5 eşit. Artan yok, yani eşit sayıda.' },
  'c1-s3': { hint: '„Weniger" = daha az, „mehr" kelimesinin zıttı.', explanation: '„Weniger" = diğerinden daha az sayıda olması.' },
  'c1-t': { hint: 'İki sırayı say: 8 elma, 11 armut. Kısa olan sırada daha az var.', explanation: '8 < 11, bu yüzden elma daha az.' },
  'c2-s1': { hint: '„Wie viele mehr" = aradaki farkı sorar. Eşleştirdikten sonra Lena’da kaç tane arttığını bulacaksın.', explanation: '„Wie viele mehr?" toplamı değil, farkı sorar.' },
  'c2-s2': { hint: 'Lena’nın 9’undan Ben’in 6’sı kadarını çıkar: 9 − 6. Kalan fark olur.', explanation: 'Farkı bulmak için büyük sayıdan küçüğü çıkarırsın: 9 − 6.' },
  'c2-s3': { hint: '6’dan 9’a kaç adım var? 7, 8, 9 → 3 adım. Fark 3.', explanation: '9 − 6 = 3. Lena’nın 3 sticker’ı fazla.' },
  'c2-t': { hint: 'Çitteki her kuşa ağaçtan bir kuş eşle. Ağaçta artanlar farktır: 12 − 7 = 5.', explanation: '12 − 7 = 5. Ağaçta 5 kuş daha fazla.' },
  'c3-s1': { hint: 'Tim’in sırası daha kısa. Mia’nın sırasına yetişmek için eksik olan sayı = fark.', explanation: 'Eksik olan miktar, iki grup arasındaki farktır.' },
  'c3-s2': { hint: '6’dan 10’a: 7, 8, 9, 10 → 4 adım. Tim’e 4 tane lazım.', explanation: '10 − 6 = 4. 4 tane daha alınca Tim, Mia ile eşitlenir.' },
  'c3-s3': { hint: 'Mia’nın sayısı değişmedi (10). Tim 6 + 4 = 10 oldu. İkisi de 10.', explanation: 'Tim: 6 + 4 = 10. Mia zaten 10. Artık eşitler.' },
  'c3-t': { hint: '9’dan 13’e: 10, 11, 12, 13 → 4 adım. Ya da 13 − 9.', explanation: '13 − 9 = 4. 4 sandalye eklenince iki sırada da 13 olur.' },
  'd1-s1': { hint: '„Zusammen" = toplam. İki günün taşlarını tek bir yığında topluyorsun.', explanation: 'Aranan, iki günün toplam sayısı.' },
  'd1-s2': { hint: '7’den devam et ve 5 tane say: 8, 9, 10, 11, 12.', explanation: '7 + 5 = 12. İki yığın birlikte 12 taş.' },
  'd1-s3': { hint: 'Bu soru toplam istemiyor, karşılaştırma istiyor. 7 ile 5’i karşılaştır.', explanation: '7 > 5. Aynı hikâyeye farklı sorular sorulabilir.' },
  'd1-t': { hint: '„Noch" = geriye kalan. Yani sonunda elde kalan sayı soruluyor.', explanation: 'Aranan, patladıktan sonra kalan sayı; hikâyede zaten yazan sayı değil.' },
  'd2-s1': { hint: 'Soru kitapları soruyor, yaşı değil. Sadece kitapla ilgili sayıları işaretle.', explanation: 'Kitap soruluyor, o yüzden 6 ve 3 gerekli. 8 yaş hesaba girmez.' },
  'd2-s2': { hint: 'Sadece kitap sayıları kullanılır: 6 + 3.', explanation: '6 kitabın üzerine 3 ekleniyor: 6 + 3.' },
  'd2-s3': { hint: '6’dan devam et: 7, 8, 9.', explanation: '6 + 3 = 9. Lisa’nın şimdi 9 kitabı var.' },
  'd2-t': { hint: 'Soru muffin soruyor. Sadece muffin sayıları gerekli: 15 ve 6.', explanation: 'Hesaba 15 ve 6 girer. Arkadaş sayısı ve yaş muffin sayısını değiştirmez.' },
  'd3-s1': { hint: 'Anna kalem alıyor, yani ikinci grup birinciye ekleniyor.', explanation: 'Bir şey eklenince iki grubu birleştirirsin.' },
  'd3-s2': { hint: '„Wie viele mehr" farkı sorar. Gruplar yan yana konur, artan sayılır.', explanation: 'Karşılaştırmada iki grup da durur; aranan aradaki farktır.' },
  'd3-s3': { hint: 'Tek bir grup var (12 kurabiye) ve 5’i gidiyor. Grup küçülüyor.', explanation: 'Çıkarmada tek gruptan kalan miktar bulunur.' },
  'd3-t': { hint: '„Zusammen" = toplam. Kırmızı ve mavi fincanları birleştirirsin.', explanation: '„Zusammen" derken iki gruptan tek büyük grup yaparsın.' },
};
