import type { TargetLocale } from '../types/content';

/**
 * Bedientexte im Kinderbereich. Sie folgen der ZIELSPRACHE des Content-Packs,
 * nicht der Elternoberfläche: Wer deutsche Aufgaben übt, sieht auch deutsche
 * Knöpfe.
 */
const de = {
  greeting: 'Hallo',
  continueLearning: 'Weiterlernen',
  nextTask: 'Deine nächste Aufgabe:',
  repeatTask: 'Das üben wir noch einmal:',
  allDone: 'Du hast alles geschafft! Noch einmal üben:',
  yourPlaces: 'Deine Lernorte',
  done: 'geschafft',
  next: 'als Nächstes',
  open: 'offen',
  progressOf: 'Geschafft: {done} von {total} Lektionen',
  parents: 'Eltern',
  pause: 'Pause',
  aloneNow: 'Jetzt allein: neue Aufgabe',
  readAloud: 'Vorlesen',
  slow: 'Langsam',
  noSpeech: 'Kein Vorlesen möglich – du kannst den Text lesen.',
  tip: 'Tipp',
  help: 'Hilfe',
  moreHelp: 'Mehr Hilfe',
  check: 'Fertig',
  continue: 'Weiter',
  finishLesson: 'Lektion beenden',
  correct: 'Richtig!',
  notYet: 'Noch nicht ganz.',
  finished: 'Fertig!',
  youPractised: 'Du hast geübt:',
  soloDone: 'Allein geschafft',
  withHint: 'Mit Tipp geschafft',
  transferDone: 'Neue Aufgabe allein gelöst',
  yes: 'ja',
  notYetShort: 'noch nicht',
  hintsAreOk: 'Tipps zu benutzen ist erlaubt. Beim nächsten Mal klappt mehr allein.',
  doneForToday: 'Für heute fertig',
  markedOn: '✓ markiert',
  tapHint: 'tippen',
  sortHint: '1. Ding antippen 2. Platz antippen',
  allSorted: 'Alles zugeordnet 👍',
  here: 'hierher',
  moved: 'Bewegt:',
  back: 'zurück',
  yourAnswer: 'Deine Antwort',
  clear: 'Löschen',
  reasonExtraAndMissing: 'Etwas Falsches ist markiert und etwas Passendes fehlt noch. Schau jedes Bild einzeln an.',
  reasonExtra: 'Ein markiertes Bild passt nicht zur Aufgabe. Prüfe jedes markierte Bild noch einmal.',
  reasonMissing: 'Es fehlt noch etwas. Denk daran: Du zeigst alle passenden Dinge.',
  reasonNoNumber: 'Es fehlt noch eine Zahl.',
  reasonTooBig: 'Deine Zahl ist zu groß. Zähle noch einmal langsam nach.',
  reasonTooSmall: 'Deine Zahl ist zu klein. Zähle noch einmal langsam nach.',
  reasonMoveCount: 'Die Anzahl passt noch nicht zur Geschichte. Lies noch einmal, wie viele bewegt werden.',
  reasonSort: '{n} Ding(e) liegen noch am falschen Platz. Tippe darauf, um es zurückzulegen.',
  reasonSelectOne: 'Diese Antwort passt noch nicht. Lies die Aufgabe noch einmal und vergleiche die Möglichkeiten.',
  reasonGeneric: 'Versuch es noch einmal.',
};

const en = {
  greeting: 'Hi',
  continueLearning: 'Keep learning',
  nextTask: 'Your next task:',
  repeatTask: 'Let’s practise this one again:',
  allDone: 'You finished everything! Practise again:',
  yourPlaces: 'Your learning places',
  done: 'done',
  next: 'up next',
  open: 'open',
  progressOf: 'Done: {done} of {total} lessons',
  parents: 'Parents',
  pause: 'Pause',
  aloneNow: 'On your own now: a new task',
  readAloud: 'Read aloud',
  slow: 'Slowly',
  noSpeech: 'Reading aloud is not available – you can read the text.',
  tip: 'Tip',
  help: 'Help',
  moreHelp: 'More help',
  check: 'Done',
  continue: 'Next',
  finishLesson: 'Finish lesson',
  correct: 'That’s right!',
  notYet: 'Not quite yet.',
  finished: 'All done!',
  youPractised: 'You practised:',
  soloDone: 'Done on your own',
  withHint: 'Done with a tip',
  transferDone: 'New task solved alone',
  yes: 'yes',
  notYetShort: 'not yet',
  hintsAreOk: 'Using tips is allowed. Next time more will work on your own.',
  doneForToday: 'Done for today',
  markedOn: '✓ marked',
  tapHint: 'tap',
  sortHint: '1. tap a thing 2. tap a place',
  allSorted: 'Everything sorted 👍',
  here: 'put here',
  moved: 'Moved:',
  back: 'back',
  yourAnswer: 'Your answer',
  clear: 'Clear',
  reasonExtraAndMissing: 'Something wrong is marked and something that fits is still missing. Look at each picture by itself.',
  reasonExtra: 'One marked picture does not fit the task. Check each marked picture again.',
  reasonMissing: 'Something is still missing. Remember: you show every thing that fits.',
  reasonNoNumber: 'A number is still missing.',
  reasonTooBig: 'Your number is too big. Count again slowly.',
  reasonTooSmall: 'Your number is too small. Count again slowly.',
  reasonMoveCount: 'The amount does not match the story yet. Read again how many are moved.',
  reasonSort: '{n} thing(s) are still in the wrong place. Tap one to put it back.',
  reasonSelectOne: 'That answer does not fit yet. Read the task again and compare the choices.',
  reasonGeneric: 'Try again.',
};

export type ChildStrings = { [K in keyof typeof de]: string };

const byLocale: Record<TargetLocale, ChildStrings> = { 'de-DE': de, 'en-US': en };

export function childT(locale: TargetLocale): ChildStrings {
  return byLocale[locale];
}
