import type { Lesson } from '../types/content';

/**
 * Modul D – Was ist in der Aufgabe gefragt?
 * Fokus: gesuchte Information erkennen, nötige Zahlen auswählen (mit Ablenkzahlen),
 * passendes bildliches Modell zur Frage wählen.
 */
export const moduleDLessons: Lesson[] = [
  {
    id: 'd1',
    moduleId: 'D',
    skillId: 'frage-erkennen',
    title: 'Was will die Frage wissen?',
    objective: 'Ich lese die Frage genau und sage, welche Information gesucht ist.',
    story: 'Paul sammelt Steine. Am Montag findet er 7 Steine. Am Dienstag findet er 5 Steine.',
    steps: [
      {
        id: 'd1-s1',
        interactionType: 'select-one',
        instruction: 'Die Frage lautet: „Wie viele Steine hat Paul zusammen?" Was sollst du herausfinden?',
        context: 'Paul findet am Montag 7 Steine und am Dienstag 5 Steine.',
        items: [
          { id: 'f1', label: 'Die Anzahl aller Steine von Montag und Dienstag.' },
          { id: 'f2', label: 'Wie viele Steine er nur am Montag gefunden hat.' },
          { id: 'f3', label: 'An welchem Tag er mehr gefunden hat.' },
        ],
        correctAnswer: 'f1',
        hint: 'Achte auf das Wort „zusammen".',
        hintDetail: '„Zusammen" heißt: beide Tage in einer Menge. Du legst die Steine von Montag und Dienstag in einen Haufen.',
        explanation: 'Gesucht ist die Gesamtzahl aus beiden Tagen.',
      },
      {
        id: 'd1-s2',
        interactionType: 'number-input',
        instruction: 'Wie viele Steine hat Paul zusammen?',
        context: 'Montag: 7 Steine. Dienstag: 5 Steine.',
        unit: 'Steine',
        correctAnswer: 12,
        hint: 'Lege beide Mengen zusammen.',
        hintDetail: 'Beginne bei 7 und zähle die 5 Steine vom Dienstag dazu: 8, 9, 10, 11, 12.',
        explanation: '7 + 5 = 12. Beide Haufen zusammen sind 12 Steine.',
      },
      {
        id: 'd1-s3',
        interactionType: 'select-one',
        instruction: 'Jetzt lautet die Frage: „An welchem Tag hat Paul mehr Steine gefunden?" Was ist die Antwort?',
        context: 'Montag: 7 Steine. Dienstag: 5 Steine.',
        sceneGroups: [
          { label: 'Montag', emoji: '🪨', count: 7 },
          { label: 'Dienstag', emoji: '🪨', count: 5 },
        ],
        items: [
          { id: 'g1', label: 'Am Montag.' },
          { id: 'g2', label: 'Am Dienstag.' },
          { id: 'g3', label: 'An beiden Tagen gleich viel.' },
        ],
        correctAnswer: 'g1',
        hint: 'Diese Frage will keine Summe, sondern einen Vergleich.',
        hintDetail: 'Vergleiche 7 und 5. Die größere Zahl gehört zum Tag mit mehr Steinen.',
        explanation: '7 ist größer als 5. Dieselbe Geschichte kann verschiedene Fragen haben.',
      },
    ],
    transferTask: {
      id: 'd1-t',
      interactionType: 'select-one',
      instruction: 'Was sollst du herausfinden?',
      context: 'Nina hat 9 Luftballons. 4 Luftballons platzen. Frage: Wie viele Luftballons hat Nina noch?',
      items: [
        { id: 'h1', label: 'Wie viele Luftballons übrig sind.' },
        { id: 'h2', label: 'Wie viele Luftballons geplatzt sind.' },
        { id: 'h3', label: 'Wie viele Luftballons Nina gekauft hat.' },
      ],
      correctAnswer: 'h1',
      hint: 'Achte auf das Wort „noch".',
      hintDetail: '„Noch" fragt nach dem Rest: Was ist am Ende übrig? Die Zahl 4 steht schon in der Geschichte.',
      explanation: 'Gesucht ist der Rest nach dem Platzen, nicht die Zahl aus der Geschichte.',
    },
  },

  {
    id: 'd2',
    moduleId: 'D',
    skillId: 'zahlen-auswaehlen',
    title: 'Welche Zahlen brauche ich?',
    objective: 'Ich erkenne, welche Zahlen zur Frage gehören – und welche ich nicht brauche.',
    story: 'In Aufgaben stehen manchmal Zahlen, die man für die Rechnung gar nicht braucht.',
    steps: [
      {
        id: 'd2-s1',
        interactionType: 'select-multiple',
        instruction: 'Markiere die Zahlen, die du für die Rechnung brauchst.',
        context: 'Lisa ist 8 Jahre alt. Sie hat 6 Bücher. Sie kauft 3 Bücher dazu. Frage: Wie viele Bücher hat Lisa jetzt?',
        items: [
          { id: 'j8', label: '8 Jahre' },
          { id: 'b6', label: '6 Bücher' },
          { id: 'b3', label: '3 Bücher' },
        ],
        correctAnswer: ['b6', 'b3'],
        hint: 'Die Frage geht um Bücher, nicht um das Alter.',
        hintDetail: 'Lies die Frage: „Wie viele Bücher hat Lisa jetzt?" Nur Zahlen, die Bücher zählen, gehören zur Rechnung. Das Alter ändert die Bücherzahl nicht.',
        explanation: 'Gesucht sind Bücher, also brauchst du 6 und 3. Die 8 Jahre gehören nicht zur Rechnung.',
      },
      {
        id: 'd2-s2',
        interactionType: 'select-one',
        instruction: 'Welche Rechnung passt?',
        context: 'Lisa hat 6 Bücher und kauft 3 Bücher dazu.',
        items: [
          { id: 'r1', label: '6 + 3' },
          { id: 'r2', label: '8 + 6' },
          { id: 'r3', label: '8 − 3' },
        ],
        correctAnswer: 'r1',
        hint: 'Benutze nur die Zahlen, die Bücher zählen.',
        hintDetail: 'Lisa hat 6 Bücher. Sie kauft 3 dazu, also wird ihre Menge größer: 6 + 3.',
        explanation: 'Zu den 6 Büchern kommen 3 dazu: 6 + 3.',
      },
      {
        id: 'd2-s3',
        interactionType: 'number-input',
        instruction: 'Wie viele Bücher hat Lisa jetzt?',
        context: 'Lisa hat 6 Bücher und kauft 3 Bücher dazu.',
        unit: 'Bücher',
        correctAnswer: 9,
        hint: 'Zähle von 6 weiter.',
        hintDetail: 'Beginne bei 6 und zähle 3 dazu: 7, 8, 9.',
        explanation: '6 + 3 = 9. Lisa hat jetzt 9 Bücher.',
      },
    ],
    transferTask: {
      id: 'd2-t',
      interactionType: 'select-multiple',
      instruction: 'Markiere die Zahlen, die du für die Rechnung brauchst.',
      context: 'Tom hat 4 Freunde eingeladen. Er ist 9 Jahre alt. Auf dem Tisch liegen 15 Muffins. Die Kinder essen 6 Muffins. Frage: Wie viele Muffins liegen noch auf dem Tisch?',
      items: [
        { id: 'z4', label: '4 Freunde' },
        { id: 'z9', label: '9 Jahre' },
        { id: 'z15', label: '15 Muffins' },
        { id: 'z6', label: '6 Muffins' },
      ],
      correctAnswer: ['z15', 'z6'],
      hint: 'Wonach fragt die Aufgabe – nach Muffins oder nach Kindern?',
      hintDetail: 'Gefragt sind Muffins auf dem Tisch. Nur Zahlen, die Muffins zählen, gehören zur Rechnung: 15 und 6.',
      explanation: 'Es gehören 15 und 6 zur Rechnung. Freunde und Alter ändern die Muffinzahl nicht.',
    },
  },

  {
    id: 'd3',
    moduleId: 'D',
    skillId: 'modell-waehlen',
    title: 'Welches Bild passt zur Frage?',
    objective: 'Ich wähle das passende Bild-Modell: zusammenlegen, wegnehmen oder vergleichen.',
    story: 'Zu jeder Frage passt ein Bild: zusammenlegen, wegnehmen oder zwei Mengen vergleichen.',
    steps: [
      {
        id: 'd3-s1',
        interactionType: 'select-one',
        instruction: 'Welches Bild passt zur Frage?',
        context: 'Anna hat 5 Stifte. Sie bekommt 4 Stifte dazu. Wie viele Stifte hat sie jetzt?',
        items: [
          { id: 'm1', label: 'Zwei Gruppen werden zusammengelegt.', emoji: '🟢🟢🟢🟢🟢 ➕ 🟢🟢🟢🟢' },
          { id: 'm2', label: 'Von einer Gruppe wird etwas weggenommen.', emoji: '🟢🟢🟢🟢🟢 ➖' },
          { id: 'm3', label: 'Zwei Gruppen werden nebeneinander verglichen.', emoji: '🟢🟢🟢 ↔ 🔵🔵' },
        ],
        correctAnswer: 'm1',
        hint: 'Anna bekommt Stifte dazu. Wird ihre Menge größer oder kleiner?',
        hintDetail: 'Dazubekommen heißt: Eine zweite Gruppe kommt zur ersten. Beide zusammen ergeben die neue Menge.',
        explanation: 'Beim Dazubekommen legst du zwei Gruppen zusammen.',
      },
      {
        id: 'd3-s2',
        interactionType: 'select-one',
        instruction: 'Welches Bild passt zur Frage?',
        context: 'In Klasse A sind 14 Kinder, in Klasse B sind 11 Kinder. Wie viele Kinder mehr sind in Klasse A?',
        items: [
          { id: 'n1', label: 'Zwei Gruppen werden nebeneinander verglichen.', emoji: '🟦🟦🟦 ↔ 🟧🟧' },
          { id: 'n2', label: 'Zwei Gruppen werden zusammengelegt.', emoji: '🟦🟦🟦 ➕ 🟧🟧' },
          { id: 'n3', label: 'Von einer Gruppe wird etwas weggenommen.', emoji: '🟦🟦🟦 ➖' },
        ],
        correctAnswer: 'n1',
        hint: '„Wie viele mehr" fragt nach dem Unterschied.',
        hintDetail: 'Die Kinder gehen nicht weg und kommen nicht dazu. Beide Klassen bleiben. Du legst die Reihen nebeneinander und schaust, was übrig bleibt.',
        explanation: 'Beim Vergleichen bleiben beide Mengen bestehen. Gesucht ist der Unterschied.',
      },
      {
        id: 'd3-s3',
        interactionType: 'select-one',
        instruction: 'Welches Bild passt zur Frage?',
        context: 'Von 12 Keksen isst Ben 5 Kekse. Wie viele Kekse bleiben?',
        items: [
          { id: 'o1', label: 'Von einer Gruppe wird etwas weggenommen.', emoji: '🍪🍪🍪🍪 ➖ 🍪🍪' },
          { id: 'o2', label: 'Zwei Gruppen werden zusammengelegt.', emoji: '🍪🍪 ➕ 🍪🍪' },
          { id: 'o3', label: 'Zwei Gruppen werden nebeneinander verglichen.', emoji: '🍪🍪🍪 ↔ 🍪' },
        ],
        correctAnswer: 'o1',
        hint: 'Gegessene Kekse sind nicht mehr da.',
        hintDetail: 'Es gibt nur eine Gruppe: die 12 Kekse. Davon verschwinden 5. Die Gruppe wird kleiner.',
        explanation: 'Beim Wegnehmen bleibt ein Rest von einer einzigen Gruppe.',
      },
    ],
    transferTask: {
      id: 'd3-t',
      interactionType: 'select-one',
      instruction: 'Welches Bild passt zur Frage?',
      context: 'Im Regal stehen 7 rote und 6 blaue Tassen. Wie viele Tassen sind es zusammen?',
      items: [
        { id: 'p1', label: 'Zwei Gruppen werden zusammengelegt.', emoji: '🔴🔴🔴 ➕ 🔵🔵🔵' },
        { id: 'p2', label: 'Von einer Gruppe wird etwas weggenommen.', emoji: '🔴🔴🔴 ➖' },
        { id: 'p3', label: 'Zwei Gruppen werden nebeneinander verglichen.', emoji: '🔴🔴🔴 ↔ 🔵🔵' },
      ],
      correctAnswer: 'p1',
      hint: 'Achte auf das Wort „zusammen".',
      hintDetail: 'Die roten und die blauen Tassen stehen im selben Regal. Für die Gesamtzahl legst du beide Gruppen zusammen.',
      explanation: 'Bei „zusammen" bildest du aus zwei Gruppen eine große Menge.',
    },
  },
];
