import type { Lesson } from '../types/content';

/**
 * Modul C – Vergleichen.
 * Fokus: zwei Mengen nebeneinander legen, Unterschied als Rest der Paarbildung verstehen.
 */
export const moduleCLessons: Lesson[] = [
  {
    id: 'c1',
    moduleId: 'C',
    skillId: 'vergleichen-mehr-weniger',
    titleDe: 'Mehr, weniger oder gleich viele?',
    objectiveDe: 'Ich vergleiche zwei Mengen und sage, wovon es mehr, weniger oder gleich viel gibt.',
    storyDe: 'Beim Vergleichen legst du zwei Mengen nebeneinander und schaust, welche länger ist.',
    steps: [
      {
        id: 'c1-s1',
        interactionType: 'select-one',
        instructionDe: 'Wovon gibt es mehr?',
        sceneGroups: [
          { labelDe: 'Fische', emoji: '🐟', count: 6 },
          { labelDe: 'Schildkröten', emoji: '🐢', count: 4 },
        ],
        items: [
          { id: 'g1', labelDe: 'Es gibt mehr Fische.' },
          { id: 'g2', labelDe: 'Es gibt mehr Schildkröten.' },
          { id: 'g3', labelDe: 'Es gibt gleich viele.' },
        ],
        correctAnswer: 'g1',
        hintDe: 'Bilde Paare: ein Fisch und eine Schildkröte. Was bleibt übrig?',
        hintDetailDe: 'Die Reihen liegen untereinander. Zähle: 6 Fische, 4 Schildkröten. Die Fischreihe ist länger, es bleiben Fische übrig.',
        hintTr: 'Eşleştir: bir balık – bir kaplumbağa. Artanlar hangi taraftaysa orası daha çok.',
        explanationDe: '6 ist größer als 4. Nach dem Paarebilden bleiben 2 Fische übrig – deshalb gibt es mehr Fische.',
        explanationTr: '6 > 4. Eşleştirdikten sonra 2 balık artıyor, yani balık daha fazla.',
      },
      {
        id: 'c1-s2',
        interactionType: 'select-one',
        instructionDe: 'Wie ist es hier?',
        sceneGroups: [
          { labelDe: 'Sterne', emoji: '⭐', count: 5 },
          { labelDe: 'Herzen', emoji: '❤️', count: 5 },
        ],
        items: [
          { id: 'h1', labelDe: 'Es gibt gleich viele.' },
          { id: 'h2', labelDe: 'Es gibt mehr Sterne.' },
          { id: 'h3', labelDe: 'Es gibt mehr Herzen.' },
        ],
        correctAnswer: 'h1',
        hintDe: 'Passt zu jedem Stern genau ein Herz?',
        hintDetailDe: 'Lege gedanklich Paare: Stern–Herz. Wenn nichts übrig bleibt, sind es gleich viele.',
        hintTr: 'Her yıldıza bir kalp düşüyor mu? Hiçbir şey artmıyorsa sayılar eşittir.',
        explanationDe: '5 und 5 sind gleich. Es bleibt nichts übrig, also gleich viele.',
        explanationTr: '5 ve 5 eşit. Artan yok, yani eşit sayıda.',
      },
      {
        id: 'c1-s3',
        interactionType: 'select-one',
        instructionDe: 'Was bedeutet „weniger"?',
        items: [
          { id: 'w1', labelDe: 'Es sind nicht so viele.' },
          { id: 'w2', labelDe: 'Es sind mehr.' },
          { id: 'w3', labelDe: 'Es sind genau gleich viele.' },
        ],
        correctAnswer: 'w1',
        hintDe: 'Weniger ist das Gegenteil von mehr.',
        hintDetailDe: 'Wenn eine Reihe kürzer ist als die andere, sind dort weniger Dinge – also nicht so viele.',
        hintTr: '„Weniger" = daha az, „mehr" kelimesinin zıttı.',
        explanationDe: '„Weniger" heißt: Von dieser Sache gibt es nicht so viele wie von der anderen.',
        explanationTr: '„Weniger" = diğerinden daha az sayıda olması.',
      },
    ],
    transferTask: {
      id: 'c1-t',
      interactionType: 'select-one',
      instructionDe: 'Wovon gibt es weniger?',
      sceneGroups: [
        { labelDe: 'Äpfel', emoji: '🍎', count: 8 },
        { labelDe: 'Birnen', emoji: '🍐', count: 11 },
      ],
      items: [
        { id: 'x1', labelDe: 'Es gibt weniger Äpfel.' },
        { id: 'x2', labelDe: 'Es gibt weniger Birnen.' },
        { id: 'x3', labelDe: 'Es gibt gleich viele.' },
      ],
      correctAnswer: 'x1',
      hintDe: 'Welche Reihe ist kürzer?',
      hintDetailDe: 'Zähle beide Reihen: 8 Äpfel, 11 Birnen. Die kürzere Reihe hat weniger.',
      hintTr: 'İki sırayı say: 8 elma, 11 armut. Kısa olan sırada daha az var.',
      explanationDe: '8 ist kleiner als 11. Deshalb gibt es weniger Äpfel.',
      explanationTr: '8 < 11, bu yüzden elma daha az.',
    },
  },

  {
    id: 'c2',
    moduleId: 'C',
    skillId: 'unterschied-bestimmen',
    titleDe: 'Wie viele mehr?',
    objectiveDe: 'Ich verstehe, dass „wie viele mehr" nach dem Unterschied zwischen zwei Mengen fragt.',
    storyDe: 'Lena hat 9 Sticker. Ben hat 6 Sticker.',
    steps: [
      {
        id: 'c2-s1',
        interactionType: 'select-one',
        instructionDe: 'Was sollst du herausfinden?',
        contextDe: 'Lena hat 9 Sticker. Ben hat 6 Sticker. Wie viele Sticker hat Lena mehr als Ben?',
        sceneGroups: [
          { labelDe: 'Lena', emoji: '🌟', count: 9 },
          { labelDe: 'Ben', emoji: '🌟', count: 6 },
        ],
        items: [
          { id: 'u1', labelDe: 'Den Unterschied zwischen 9 und 6.' },
          { id: 'u2', labelDe: 'Wie viele Sticker beide zusammen haben.' },
          { id: 'u3', labelDe: 'Wie viele Sticker Ben kaufen möchte.' },
        ],
        correctAnswer: 'u1',
        hintDe: 'Die Frage vergleicht Lena und Ben.',
        hintDetailDe: 'Bilde Paare: Zu jedem Sticker von Ben gehört einer von Lena. Gefragt ist, wie viele bei Lena übrig bleiben – das ist der Unterschied.',
        hintTr: '„Wie viele mehr" = aradaki farkı sorar. Eşleştirdikten sonra Lena’da kaç tane arttığını bulacaksın.',
        explanationDe: '„Wie viele mehr?" fragt nach dem Unterschied, nicht nach der Summe.',
        explanationTr: '„Wie viele mehr?" toplamı değil, farkı sorar.',
      },
      {
        id: 'c2-s2',
        interactionType: 'select-one',
        instructionDe: 'Welche Rechnung passt?',
        contextDe: 'Lena hat 9 Sticker. Ben hat 6 Sticker.',
        items: [
          { id: 'v1', labelDe: '9 − 6' },
          { id: 'v2', labelDe: '9 + 6' },
          { id: 'v3', labelDe: '6 + 6' },
        ],
        correctAnswer: 'v1',
        hintDe: 'Du suchst den Rest, der bei Lena übrig bleibt.',
        hintDetailDe: 'Nimm von Lenas 9 Stickern so viele weg, wie Ben hat (6). Was übrig bleibt, ist der Unterschied: 9 − 6.',
        hintTr: 'Lena’nın 9’undan Ben’in 6’sı kadarını çıkar: 9 − 6. Kalan fark olur.',
        explanationDe: 'Den Unterschied findest du, indem du die kleinere Menge von der größeren wegnimmst: 9 − 6.',
        explanationTr: 'Farkı bulmak için büyük sayıdan küçüğü çıkarırsın: 9 − 6.',
      },
      {
        id: 'c2-s3',
        interactionType: 'number-input',
        instructionDe: 'Wie viele Sticker hat Lena mehr als Ben?',
        contextDe: 'Lena hat 9 Sticker. Ben hat 6 Sticker.',
        unitDe: 'Sticker',
        correctAnswer: 3,
        hintDe: 'Zähle von 6 bis 9 weiter. Wie viele Schritte sind das?',
        hintDetailDe: 'Von 6 zu 9: 7 (1 Schritt), 8 (2 Schritte), 9 (3 Schritte). Der Unterschied ist 3.',
        hintTr: '6’dan 9’a kaç adım var? 7, 8, 9 → 3 adım. Fark 3.',
        explanationDe: '9 − 6 = 3. Lena hat 3 Sticker mehr als Ben.',
        explanationTr: '9 − 6 = 3. Lena’nın 3 sticker’ı fazla.',
      },
    ],
    transferTask: {
      id: 'c2-t',
      interactionType: 'number-input',
      instructionDe: 'Wie viele Vögel sitzen mehr auf dem Baum als auf dem Zaun?',
      contextDe: 'Auf dem Baum sitzen 12 Vögel. Auf dem Zaun sitzen 7 Vögel.',
      unitDe: 'Vögel',
      correctAnswer: 5,
      hintDe: 'Vergleiche die beiden Mengen.',
      hintDetailDe: 'Zu jedem Vogel auf dem Zaun gehört einer auf dem Baum. Übrig bleiben die zusätzlichen Vögel auf dem Baum: 12 − 7.',
      hintTr: 'Çitteki her kuşa ağaçtan bir kuş eşle. Ağaçta artanlar farktır: 12 − 7 = 5.',
      explanationDe: '12 − 7 = 5. Auf dem Baum sitzen 5 Vögel mehr.',
      explanationTr: '12 − 7 = 5. Ağaçta 5 kuş daha fazla.',
    },
  },

  {
    id: 'c3',
    moduleId: 'C',
    skillId: 'ausgleichen',
    titleDe: 'Gleich viele machen',
    objectiveDe: 'Ich finde heraus, wie viele fehlen, damit zwei Mengen gleich groß sind.',
    storyDe: 'Mia hat 10 Bausteine. Tim hat 6 Bausteine. Beide wollen gleich viele haben.',
    steps: [
      {
        id: 'c3-s1',
        interactionType: 'select-one',
        instructionDe: 'Wie findest du heraus, wie viele Bausteine Tim noch braucht?',
        contextDe: 'Mia hat 10 Bausteine. Tim hat 6 Bausteine.',
        sceneGroups: [
          { labelDe: 'Mia', emoji: '🟦', count: 10 },
          { labelDe: 'Tim', emoji: '🟦', count: 6 },
        ],
        items: [
          { id: 'a1', labelDe: 'Ich suche den Unterschied zwischen 10 und 6.' },
          { id: 'a2', labelDe: 'Ich rechne 10 + 6.' },
          { id: 'a3', labelDe: 'Ich zähle alle Bausteine zusammen.' },
        ],
        correctAnswer: 'a1',
        hintDe: 'Tims Reihe ist kürzer. Wie viel fehlt bis zu Mias Reihe?',
        hintDetailDe: 'Lege beide Reihen untereinander. Der leere Platz am Ende von Tims Reihe zeigt, wie viele fehlen. Das ist der Unterschied.',
        hintTr: 'Tim’in sırası daha kısa. Mia’nın sırasına yetişmek için eksik olan sayı = fark.',
        explanationDe: 'Die fehlende Anzahl ist der Unterschied zwischen beiden Mengen.',
        explanationTr: 'Eksik olan miktar, iki grup arasındaki farktır.',
      },
      {
        id: 'c3-s2',
        interactionType: 'number-input',
        instructionDe: 'Wie viele Bausteine braucht Tim noch?',
        contextDe: 'Mia hat 10 Bausteine. Tim hat 6 Bausteine.',
        unitDe: 'Bausteine',
        correctAnswer: 4,
        hintDe: 'Zähle von 6 bis 10 weiter.',
        hintDetailDe: 'Von 6 zu 10: 7, 8, 9, 10. Das sind 4 Schritte. Tim braucht 4 Bausteine.',
        hintTr: '6’dan 10’a: 7, 8, 9, 10 → 4 adım. Tim’e 4 tane lazım.',
        explanationDe: '10 − 6 = 4. Mit 4 weiteren Bausteinen hat Tim genauso viele wie Mia.',
        explanationTr: '10 − 6 = 4. 4 tane daha alınca Tim, Mia ile eşitlenir.',
      },
      {
        id: 'c3-s3',
        interactionType: 'select-one',
        instructionDe: 'Wie viele Bausteine hat dann jedes Kind?',
        contextDe: 'Tim hat 4 Bausteine dazubekommen.',
        items: [
          { id: 'e1', labelDe: 'Jedes Kind hat 10 Bausteine.' },
          { id: 'e2', labelDe: 'Jedes Kind hat 16 Bausteine.' },
          { id: 'e3', labelDe: 'Jedes Kind hat 6 Bausteine.' },
        ],
        correctAnswer: 'e1',
        hintDe: 'Mias Anzahl hat sich nicht verändert.',
        hintDetailDe: 'Mia hatte 10 und hat nichts abgegeben. Tim hatte 6 und bekam 4 dazu: 6 + 4 = 10. Beide haben 10.',
        hintTr: 'Mia’nın sayısı değişmedi (10). Tim 6 + 4 = 10 oldu. İkisi de 10.',
        explanationDe: 'Tim: 6 + 4 = 10. Mia hat weiterhin 10. Jetzt sind beide gleich.',
        explanationTr: 'Tim: 6 + 4 = 10. Mia zaten 10. Artık eşitler.',
      },
    ],
    transferTask: {
      id: 'c3-t',
      interactionType: 'number-input',
      instructionDe: 'Wie viele Stühle müssen noch in Reihe B dazu, damit beide Reihen gleich viele haben?',
      contextDe: 'In Reihe A stehen 13 Stühle. In Reihe B stehen 9 Stühle.',
      unitDe: 'Stühle',
      correctAnswer: 4,
      hintDe: 'Wie weit ist es von 9 bis 13?',
      hintDetailDe: 'Zähle von 9 weiter: 10, 11, 12, 13. Das sind 4 Schritte. Oder rechne 13 − 9.',
      hintTr: '9’dan 13’e: 10, 11, 12, 13 → 4 adım. Ya da 13 − 9.',
      explanationDe: '13 − 9 = 4. Mit 4 Stühlen mehr stehen in beiden Reihen 13 Stühle.',
      explanationTr: '13 − 9 = 4. 4 sandalye eklenince iki sırada da 13 olur.',
    },
  },
];
