import type { Lesson } from '../types/content';

/**
 * Modul C – Vergleichen.
 * Fokus: zwei Mengen nebeneinander legen, Unterschied als Rest der Paarbildung verstehen.
 */
export const moduleCLessons: Lesson[] = [
  {
    id: 'c1',
    moduleId: 'C',
    skillId: 'vergleichen-mehr-weniger',
    title: 'Mehr, weniger oder gleich viele?',
    objective: 'Ich vergleiche zwei Mengen und sage, wovon es mehr, weniger oder gleich viel gibt.',
    story: 'Beim Vergleichen legst du zwei Mengen nebeneinander und schaust, welche länger ist.',
    steps: [
      {
        id: 'c1-s1',
        interactionType: 'select-one',
        instruction: 'Wovon gibt es mehr?',
        sceneGroups: [
          { label: 'Fische', emoji: '🐟', count: 6 },
          { label: 'Schildkröten', emoji: '🐢', count: 4 },
        ],
        items: [
          { id: 'g1', label: 'Es gibt mehr Fische.' },
          { id: 'g2', label: 'Es gibt mehr Schildkröten.' },
          { id: 'g3', label: 'Es gibt gleich viele.' },
        ],
        correctAnswer: 'g1',
        hint: 'Bilde Paare: ein Fisch und eine Schildkröte. Was bleibt übrig?',
        hintDetail: 'Die Reihen liegen untereinander. Zähle: 6 Fische, 4 Schildkröten. Die Fischreihe ist länger, es bleiben Fische übrig.',
        explanation: '6 ist größer als 4. Nach dem Paarebilden bleiben 2 Fische übrig – deshalb gibt es mehr Fische.',
      },
      {
        id: 'c1-s2',
        interactionType: 'select-one',
        instruction: 'Wie ist es hier?',
        sceneGroups: [
          { label: 'Sterne', emoji: '⭐', count: 5 },
          { label: 'Herzen', emoji: '❤️', count: 5 },
        ],
        items: [
          { id: 'h1', label: 'Es gibt gleich viele.' },
          { id: 'h2', label: 'Es gibt mehr Sterne.' },
          { id: 'h3', label: 'Es gibt mehr Herzen.' },
        ],
        correctAnswer: 'h1',
        hint: 'Passt zu jedem Stern genau ein Herz?',
        hintDetail: 'Lege gedanklich Paare: Stern–Herz. Wenn nichts übrig bleibt, sind es gleich viele.',
        explanation: '5 und 5 sind gleich. Es bleibt nichts übrig, also gleich viele.',
      },
      {
        id: 'c1-s3',
        interactionType: 'select-one',
        instruction: 'Was bedeutet „weniger"?',
        items: [
          { id: 'w1', label: 'Es sind nicht so viele.' },
          { id: 'w2', label: 'Es sind mehr.' },
          { id: 'w3', label: 'Es sind genau gleich viele.' },
        ],
        correctAnswer: 'w1',
        hint: 'Weniger ist das Gegenteil von mehr.',
        hintDetail: 'Wenn eine Reihe kürzer ist als die andere, sind dort weniger Dinge – also nicht so viele.',
        explanation: '„Weniger" heißt: Von dieser Sache gibt es nicht so viele wie von der anderen.',
      },
    ],
    transferTask: {
      id: 'c1-t',
      interactionType: 'select-one',
      instruction: 'Wovon gibt es weniger?',
      sceneGroups: [
        { label: 'Äpfel', emoji: '🍎', count: 8 },
        { label: 'Birnen', emoji: '🍐', count: 11 },
      ],
      items: [
        { id: 'x1', label: 'Es gibt weniger Äpfel.' },
        { id: 'x2', label: 'Es gibt weniger Birnen.' },
        { id: 'x3', label: 'Es gibt gleich viele.' },
      ],
      correctAnswer: 'x1',
      hint: 'Welche Reihe ist kürzer?',
      hintDetail: 'Zähle beide Reihen: 8 Äpfel, 11 Birnen. Die kürzere Reihe hat weniger.',
      explanation: '8 ist kleiner als 11. Deshalb gibt es weniger Äpfel.',
    },
  },

  {
    id: 'c2',
    moduleId: 'C',
    skillId: 'unterschied-bestimmen',
    title: 'Wie viele mehr?',
    objective: 'Ich verstehe, dass „wie viele mehr" nach dem Unterschied zwischen zwei Mengen fragt.',
    story: 'Lena hat 9 Sticker. Ben hat 6 Sticker.',
    steps: [
      {
        id: 'c2-s1',
        interactionType: 'select-one',
        instruction: 'Was sollst du herausfinden?',
        context: 'Lena hat 9 Sticker. Ben hat 6 Sticker. Wie viele Sticker hat Lena mehr als Ben?',
        sceneGroups: [
          { label: 'Lena', emoji: '🌟', count: 9 },
          { label: 'Ben', emoji: '🌟', count: 6 },
        ],
        items: [
          { id: 'u1', label: 'Den Unterschied zwischen 9 und 6.' },
          { id: 'u2', label: 'Wie viele Sticker beide zusammen haben.' },
          { id: 'u3', label: 'Wie viele Sticker Ben kaufen möchte.' },
        ],
        correctAnswer: 'u1',
        hint: 'Die Frage vergleicht Lena und Ben.',
        hintDetail: 'Bilde Paare: Zu jedem Sticker von Ben gehört einer von Lena. Gefragt ist, wie viele bei Lena übrig bleiben – das ist der Unterschied.',
        explanation: '„Wie viele mehr?" fragt nach dem Unterschied, nicht nach der Summe.',
      },
      {
        id: 'c2-s2',
        interactionType: 'select-one',
        instruction: 'Welche Rechnung passt?',
        context: 'Lena hat 9 Sticker. Ben hat 6 Sticker.',
        items: [
          { id: 'v1', label: '9 − 6' },
          { id: 'v2', label: '9 + 6' },
          { id: 'v3', label: '6 + 6' },
        ],
        correctAnswer: 'v1',
        hint: 'Du suchst den Rest, der bei Lena übrig bleibt.',
        hintDetail: 'Nimm von Lenas 9 Stickern so viele weg, wie Ben hat (6). Was übrig bleibt, ist der Unterschied: 9 − 6.',
        explanation: 'Den Unterschied findest du, indem du die kleinere Menge von der größeren wegnimmst: 9 − 6.',
      },
      {
        id: 'c2-s3',
        interactionType: 'number-input',
        instruction: 'Wie viele Sticker hat Lena mehr als Ben?',
        context: 'Lena hat 9 Sticker. Ben hat 6 Sticker.',
        unit: 'Sticker',
        correctAnswer: 3,
        hint: 'Zähle von 6 bis 9 weiter. Wie viele Schritte sind das?',
        hintDetail: 'Von 6 zu 9: 7 (1 Schritt), 8 (2 Schritte), 9 (3 Schritte). Der Unterschied ist 3.',
        explanation: '9 − 6 = 3. Lena hat 3 Sticker mehr als Ben.',
      },
    ],
    transferTask: {
      id: 'c2-t',
      interactionType: 'number-input',
      instruction: 'Wie viele Vögel sitzen mehr auf dem Baum als auf dem Zaun?',
      context: 'Auf dem Baum sitzen 12 Vögel. Auf dem Zaun sitzen 7 Vögel.',
      unit: 'Vögel',
      correctAnswer: 5,
      hint: 'Vergleiche die beiden Mengen.',
      hintDetail: 'Zu jedem Vogel auf dem Zaun gehört einer auf dem Baum. Übrig bleiben die zusätzlichen Vögel auf dem Baum: 12 − 7.',
      explanation: '12 − 7 = 5. Auf dem Baum sitzen 5 Vögel mehr.',
    },
  },

  {
    id: 'c3',
    moduleId: 'C',
    skillId: 'ausgleichen',
    title: 'Gleich viele machen',
    objective: 'Ich finde heraus, wie viele fehlen, damit zwei Mengen gleich groß sind.',
    story: 'Mia hat 10 Bausteine. Tim hat 6 Bausteine. Beide wollen gleich viele haben.',
    steps: [
      {
        id: 'c3-s1',
        interactionType: 'select-one',
        instruction: 'Wie findest du heraus, wie viele Bausteine Tim noch braucht?',
        context: 'Mia hat 10 Bausteine. Tim hat 6 Bausteine.',
        sceneGroups: [
          { label: 'Mia', emoji: '🟦', count: 10 },
          { label: 'Tim', emoji: '🟦', count: 6 },
        ],
        items: [
          { id: 'a1', label: 'Ich suche den Unterschied zwischen 10 und 6.' },
          { id: 'a2', label: 'Ich rechne 10 + 6.' },
          { id: 'a3', label: 'Ich zähle alle Bausteine zusammen.' },
        ],
        correctAnswer: 'a1',
        hint: 'Tims Reihe ist kürzer. Wie viel fehlt bis zu Mias Reihe?',
        hintDetail: 'Lege beide Reihen untereinander. Der leere Platz am Ende von Tims Reihe zeigt, wie viele fehlen. Das ist der Unterschied.',
        explanation: 'Die fehlende Anzahl ist der Unterschied zwischen beiden Mengen.',
      },
      {
        id: 'c3-s2',
        interactionType: 'number-input',
        instruction: 'Wie viele Bausteine braucht Tim noch?',
        context: 'Mia hat 10 Bausteine. Tim hat 6 Bausteine.',
        unit: 'Bausteine',
        correctAnswer: 4,
        hint: 'Zähle von 6 bis 10 weiter.',
        hintDetail: 'Von 6 zu 10: 7, 8, 9, 10. Das sind 4 Schritte. Tim braucht 4 Bausteine.',
        explanation: '10 − 6 = 4. Mit 4 weiteren Bausteinen hat Tim genauso viele wie Mia.',
      },
      {
        id: 'c3-s3',
        interactionType: 'select-one',
        instruction: 'Wie viele Bausteine hat dann jedes Kind?',
        context: 'Tim hat 4 Bausteine dazubekommen.',
        items: [
          { id: 'e1', label: 'Jedes Kind hat 10 Bausteine.' },
          { id: 'e2', label: 'Jedes Kind hat 16 Bausteine.' },
          { id: 'e3', label: 'Jedes Kind hat 6 Bausteine.' },
        ],
        correctAnswer: 'e1',
        hint: 'Mias Anzahl hat sich nicht verändert.',
        hintDetail: 'Mia hatte 10 und hat nichts abgegeben. Tim hatte 6 und bekam 4 dazu: 6 + 4 = 10. Beide haben 10.',
        explanation: 'Tim: 6 + 4 = 10. Mia hat weiterhin 10. Jetzt sind beide gleich.',
      },
    ],
    transferTask: {
      id: 'c3-t',
      interactionType: 'number-input',
      instruction: 'Wie viele Stühle müssen noch in Reihe B dazu, damit beide Reihen gleich viele haben?',
      context: 'In Reihe A stehen 13 Stühle. In Reihe B stehen 9 Stühle.',
      unit: 'Stühle',
      correctAnswer: 4,
      hint: 'Wie weit ist es von 9 bis 13?',
      hintDetail: 'Zähle von 9 weiter: 10, 11, 12, 13. Das sind 4 Schritte. Oder rechne 13 − 9.',
      explanation: '13 − 9 = 4. Mit 4 Stühlen mehr stehen in beiden Reihen 13 Stühle.',
    },
  },
];
