import type { Lesson } from '../types/content';

/**
 * Modul B – Dazu und weg.
 * Fokus: Die Geschichte zeigt, ob eine Menge größer oder kleiner wird.
 * Es wird bewusst KEINE Signalwort-Regel gelehrt („mehr heißt plus"),
 * sondern immer die Handlung in der Geschichte.
 */
export const moduleBLessons: Lesson[] = [
  {
    id: 'b1',
    moduleId: 'B',
    skillId: 'dazu-rechnen',
    titleDe: 'Es kommt etwas dazu',
    objectiveDe: 'Ich erkenne in der Geschichte, dass eine Menge größer wird, und finde die passende Rechnung.',
    storyDe: 'Auf dem Tisch liegen 5 Kekse. Papa legt 4 Kekse dazu.',
    steps: [
      {
        id: 'b1-s1',
        interactionType: 'move-objects',
        instructionDe: 'Lege 4 Kekse dazu auf den Tisch.',
        contextDe: 'Auf dem Tisch liegen 5 Kekse. Papa legt 4 Kekse dazu.',
        mode: 'add',
        emoji: '🍪',
        objectLabelDe: 'Keks',
        startCount: 5,
        moveCount: 4,
        sourceLabelDe: 'Papas Teller',
        targetLabelDe: 'Tisch',
        correctAnswer: 4,
        hintDe: 'Papa legt 4 Kekse dazu. Bewege genau 4 Kekse auf den Tisch.',
        hintDetailDe: 'Tippe einen Keks von Papas Teller an. Er wandert auf den Tisch. Mache das viermal – dann liegen die 4 neuen Kekse beim Rest.',
        hintTr: 'Baba 4 kurabiye ekliyor. Tam 4 kurabiyeyi masaya taşı.',
        explanationDe: 'Die 4 Kekse kommen zu den 5 Keksen dazu. Die Menge auf dem Tisch wird größer.',
        explanationTr: '4 kurabiye, 5 kurabiyenin üzerine ekleniyor. Masadaki miktar artıyor.',
      },
      {
        id: 'b1-s2',
        interactionType: 'select-one',
        instructionDe: 'Welche Rechnung passt zu der Geschichte?',
        contextDe: 'Auf dem Tisch liegen 5 Kekse. Papa legt 4 Kekse dazu.',
        items: [
          { id: 'r1', labelDe: '5 + 4' },
          { id: 'r2', labelDe: '5 − 4' },
          { id: 'r3', labelDe: '4 − 5' },
        ],
        correctAnswer: 'r1',
        hintDe: 'Auf dem Tisch liegen jetzt mehr Kekse als vorher.',
        hintDetailDe: 'Am Anfang waren 5 Kekse da. Es kommen 4 dazu. Wenn eine Menge größer wird, legst du zusammen: 5 + 4.',
        hintTr: 'Masadaki kurabiye sayısı arttı. Bir miktar artıyorsa toplama yaparsın: 5 + 4.',
        explanationDe: 'Zwei Mengen werden zusammengelegt: 5 Kekse und 4 Kekse. Deshalb 5 + 4.',
        explanationTr: 'İki grup birleşiyor: 5 kurabiye ve 4 kurabiye. Bu yüzden 5 + 4.',
      },
      {
        id: 'b1-s3',
        interactionType: 'number-input',
        instructionDe: 'Wie viele Kekse liegen jetzt auf dem Tisch?',
        contextDe: 'Auf dem Tisch liegen 5 Kekse. Papa legt 4 Kekse dazu.',
        unitDe: 'Kekse',
        correctAnswer: 9,
        hintDe: 'Zähle von 5 weiter: 6, 7, 8 …',
        hintDetailDe: 'Beginne bei 5 und zähle die 4 neuen Kekse einzeln dazu: 6, 7, 8, 9. Bei 9 hörst du auf.',
        hintTr: '5’ten devam ederek say: 6, 7, 8, 9. Cevap 9.',
        explanationDe: '5 + 4 = 9. Auf dem Tisch liegen jetzt 9 Kekse.',
        explanationTr: '5 + 4 = 9. Masada şimdi 9 kurabiye var.',
      },
    ],
    transferTask: {
      id: 'b1-t',
      interactionType: 'number-input',
      instructionDe: 'Wie viele Kinder sitzen jetzt im Bus?',
      contextDe: 'Im Bus sitzen 7 Kinder. An der Haltestelle steigen 6 Kinder ein.',
      unitDe: 'Kinder',
      correctAnswer: 13,
      hintDe: 'Steigen Kinder ein, werden es mehr oder weniger?',
      hintDetailDe: 'Einsteigen heißt: Die Kinder sind jetzt auch im Bus. Die Menge wird größer. Rechne 7 + 6.',
      hintTr: 'Otobüse binmek = sayı artar. 7 + 6 hesapla.',
      explanationDe: '7 + 6 = 13. Weil Kinder einsteigen, wird die Gruppe im Bus größer.',
      explanationTr: '7 + 6 = 13. Çocuklar bindiği için otobüsteki grup büyüyor.',
    },
  },

  {
    id: 'b2',
    moduleId: 'B',
    skillId: 'weg-rechnen',
    titleDe: 'Es geht etwas weg',
    objectiveDe: 'Ich erkenne in der Geschichte, dass eine Menge kleiner wird, und finde die passende Rechnung.',
    storyDe: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln.',
    steps: [
      {
        id: 'b2-s1',
        interactionType: 'select-one',
        instructionDe: 'Was sollst du herausfinden?',
        contextDe: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln. Wie viele Murmeln hat Mina noch?',
        items: [
          { id: 'w1', labelDe: 'Wie viele Murmeln Mina noch hat.' },
          { id: 'w2', labelDe: 'Wie viele Murmeln Ben vorher hatte.' },
          { id: 'w3', labelDe: 'Wie viele Murmeln zusammen 10 sind.' },
        ],
        correctAnswer: 'w1',
        hintDe: 'Lies die Frage am Ende der Geschichte noch einmal.',
        hintDetailDe: 'Die Frage lautet: „Wie viele Murmeln hat Mina noch?" Gesucht ist also Minas Anzahl nach dem Verschenken.',
        hintTr: 'Sorunun son cümlesini oku: „Mina’nın kaç misketi kaldı?" Yani Mina’nın kalan sayısı aranıyor.',
        explanationDe: 'Gesucht ist Minas Rest. Vorher zu wissen, was gefragt ist, macht das Rechnen leichter.',
        explanationTr: 'Aranan, Mina’da kalan miktar. Ne sorulduğunu bilmek hesabı kolaylaştırır.',
      },
      {
        id: 'b2-s2',
        interactionType: 'move-objects',
        instructionDe: 'Gib Ben 3 Murmeln.',
        contextDe: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln.',
        mode: 'remove',
        emoji: '🔵',
        objectLabelDe: 'Murmel',
        startCount: 8,
        moveCount: 3,
        sourceLabelDe: 'Mina',
        targetLabelDe: 'Ben',
        correctAnswer: 3,
        hintDe: 'Bewege genau 3 Murmeln von Mina zu Ben.',
        hintDetailDe: 'Tippe eine Murmel bei Mina an – sie wandert zu Ben. Mache das dreimal. Bei Mina bleibt der Rest liegen.',
        hintTr: 'Mina’dan Ben’e tam 3 misket taşı. Kalanlar Mina’da kalır.',
        explanationDe: 'Von Minas 8 Murmeln gehen 3 weg. Ihre Menge wird kleiner.',
        explanationTr: 'Mina’nın 8 misketinden 3’ü gidiyor. Miktarı azalıyor.',
      },
      {
        id: 'b2-s3',
        interactionType: 'select-one',
        instructionDe: 'Welche Rechnung passt?',
        contextDe: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln.',
        items: [
          { id: 'p1', labelDe: '8 − 3' },
          { id: 'p2', labelDe: '8 + 3' },
          { id: 'p3', labelDe: '3 + 3' },
        ],
        correctAnswer: 'p1',
        hintDe: 'Mina hat am Ende weniger Murmeln als am Anfang.',
        hintDetailDe: 'Mina startet mit 8. Sie gibt 3 weg. Wenn etwas weggeht, nimmst du weg: 8 − 3.',
        hintTr: 'Mina 8 ile başlıyor, 3 tanesini veriyor. Bir şey gidiyorsa çıkarma: 8 − 3.',
        explanationDe: 'Von der Menge 8 wird 3 weggenommen: 8 − 3.',
        explanationTr: '8’lik gruptan 3 çıkarılıyor: 8 − 3.',
      },
      {
        id: 'b2-s4',
        interactionType: 'number-input',
        instructionDe: 'Wie viele Murmeln hat Mina noch?',
        contextDe: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln.',
        unitDe: 'Murmeln',
        correctAnswer: 5,
        hintDe: 'Zähle von 8 rückwärts: 7, 6 …',
        hintDetailDe: 'Nimm die 3 weggegebenen Murmeln einzeln weg: 8 → 7 → 6 → 5. Es bleiben 5 Murmeln bei Mina.',
        hintTr: '8’den geriye say: 7, 6, 5. Mina’da 5 misket kalır.',
        explanationDe: '8 − 3 = 5. Bei Mina bleiben 5 Murmeln liegen.',
        explanationTr: '8 − 3 = 5. Mina’da 5 misket kalır.',
      },
    ],
    transferTask: {
      id: 'b2-t',
      interactionType: 'number-input',
      instructionDe: 'Wie viele Trauben liegen noch auf dem Teller?',
      contextDe: 'Auf dem Teller liegen 12 Trauben. Lea isst 4 Trauben.',
      unitDe: 'Trauben',
      correctAnswer: 8,
      hintDe: 'Gegessene Trauben liegen nicht mehr auf dem Teller.',
      hintDetailDe: 'Von 12 Trauben gehen 4 weg. Zähle rückwärts: 11, 10, 9, 8. Oder rechne 12 − 4.',
      hintTr: 'Yenen üzümler tabakta kalmaz. 12 − 4 = 8.',
      explanationDe: '12 − 4 = 8. Weil Lea Trauben isst, wird die Menge auf dem Teller kleiner.',
      explanationTr: '12 − 4 = 8. Lea yediği için tabaktaki miktar azalır.',
    },
  },

  {
    id: 'b3',
    moduleId: 'B',
    skillId: 'dazu-oder-weg',
    titleDe: 'Wird es mehr oder weniger?',
    objectiveDe: 'Ich entscheide anhand der Geschichte, ob eine Menge größer oder kleiner wird.',
    storyDe: 'Nicht das einzelne Wort entscheidet, sondern was in der Geschichte passiert.',
    steps: [
      {
        id: 'b3-s1',
        interactionType: 'select-one',
        instructionDe: 'Wird es mehr oder weniger?',
        contextDe: 'Tom hat 6 Sticker. Lisa schenkt ihm 5 Sticker.',
        items: [
          { id: 'm1', labelDe: 'Tom hat jetzt mehr Sticker.' },
          { id: 'm2', labelDe: 'Tom hat jetzt weniger Sticker.' },
          { id: 'm3', labelDe: 'Tom hat gleich viele Sticker.' },
        ],
        correctAnswer: 'm1',
        hintDe: 'Tom bekommt etwas dazu. Was passiert dann mit seiner Menge?',
        hintDetailDe: 'Schenken heißt: Lisa gibt, Tom bekommt. Toms Stapel wächst also.',
        hintTr: 'Lisa hediye ediyor, Tom alıyor. Yani Tom’un sayısı artıyor.',
        explanationDe: 'Tom bekommt Sticker dazu. Seine Menge wird größer.',
        explanationTr: 'Tom sticker alıyor, miktarı artıyor.',
      },
      {
        id: 'b3-s2',
        interactionType: 'select-one',
        instructionDe: 'Welche Rechnung passt?',
        contextDe: 'Sara hat 14 Karten. Sie verschenkt 5 Karten.',
        items: [
          { id: 'k1', labelDe: '14 − 5' },
          { id: 'k2', labelDe: '14 + 5' },
          { id: 'k3', labelDe: '5 + 5' },
        ],
        correctAnswer: 'k1',
        hintDe: 'Sara gibt Karten weg. Hat sie danach mehr oder weniger?',
        hintDetailDe: 'Verschenken heißt: Die Karten sind weg. Saras Menge wird kleiner, also 14 − 5.',
        hintTr: 'Sara kart veriyor, elindeki azalıyor: 14 − 5.',
        explanationDe: 'Von Saras 14 Karten gehen 5 weg: 14 − 5.',
        explanationTr: 'Sara’nın 14 kartından 5’i gidiyor: 14 − 5.',
      },
      {
        id: 'b3-s3',
        interactionType: 'number-input',
        instructionDe: 'Wie viele Karten hat Sara noch?',
        contextDe: 'Sara hat 14 Karten. Sie verschenkt 5 Karten.',
        unitDe: 'Karten',
        correctAnswer: 9,
        hintDe: 'Zähle von 14 rückwärts.',
        hintDetailDe: 'Nimm die 5 Karten einzeln weg: 13, 12, 11, 10, 9. Es bleiben 9 Karten.',
        hintTr: '14’ten geriye say: 13, 12, 11, 10, 9. Cevap 9.',
        explanationDe: '14 − 5 = 9. Sara behält 9 Karten.',
        explanationTr: '14 − 5 = 9. Sara’da 9 kart kalır.',
      },
    ],
    transferTask: {
      id: 'b3-t',
      interactionType: 'number-input',
      instructionDe: 'Wie viele Äpfel liegen noch im Korb?',
      contextDe: 'Im Korb liegen 15 Äpfel. Oma nimmt 6 Äpfel heraus.',
      unitDe: 'Äpfel',
      correctAnswer: 9,
      hintDe: 'Herausnehmen heißt: Die Äpfel sind nicht mehr im Korb.',
      hintDetailDe: 'Der Korb hat 15 Äpfel. 6 gehen heraus. Die Menge im Korb wird kleiner: 15 − 6.',
      hintTr: 'Sepetten çıkarılan elmalar sepette kalmaz: 15 − 6 = 9.',
      explanationDe: '15 − 6 = 9. Im Korb bleiben 9 Äpfel.',
      explanationTr: '15 − 6 = 9. Sepette 9 elma kalır.',
    },
  },
];
