import type { Lesson } from '../types/content';

/**
 * Modul A – Arbeitsanweisungen verstehen.
 * Fokus: Was verlangt das Wort in der Aufgabe von mir? (markieren / auswählen / zuordnen)
 */
export const moduleALessons: Lesson[] = [
  {
    id: 'a1',
    moduleId: 'A',
    skillId: 'anweisung-markieren',
    title: 'Markiere – ich zeige alle',
    objective: 'Ich weiß: „Markiere" heißt, ich zeige jedes Ding, das passt – nicht nur eines.',
    story: 'In Aufgaben steht oft das Wort „markiere". Das heißt: Du zeigst jedes Ding, das zu der Frage passt.',
    steps: [
      {
        id: 'a1-s1',
        interactionType: 'select-multiple',
        instruction: 'Markiere alle Äpfel.',
        items: [
          { id: 'ap1', label: 'Apfel', emoji: '🍎' },
          { id: 'bi1', label: 'Birne', emoji: '🍐' },
          { id: 'ap2', label: 'Apfel', emoji: '🍎' },
          { id: 'ba1', label: 'Banane', emoji: '🍌' },
          { id: 'ap3', label: 'Apfel', emoji: '🍎' },
          { id: 'bi2', label: 'Birne', emoji: '🍐' },
        ],
        correctAnswer: ['ap1', 'ap2', 'ap3'],
        hint: 'Es ist mehr als ein Apfel dabei. Schau jedes Bild einzeln an.',
        hintDetail:
          'Gehe von links nach rechts. Frage dich bei jedem Bild: Ist das ein Apfel? Wenn ja, tippe es an. Am Ende sind alle Äpfel markiert.',
        explanation: 'Es sind 3 Äpfel. Bei „markiere" zeigst du immer alle passenden Dinge.',
      },
      {
        id: 'a1-s2',
        interactionType: 'select-multiple',
        instruction: 'Markiere alle Tiere, die vier Beine haben.',
        items: [
          { id: 'hund', label: 'Hund', emoji: '🐶' },
          { id: 'vogel', label: 'Vogel', emoji: '🐦' },
          { id: 'katze', label: 'Katze', emoji: '🐱' },
          { id: 'fisch', label: 'Fisch', emoji: '🐟' },
          { id: 'pferd', label: 'Pferd', emoji: '🐴' },
        ],
        correctAnswer: ['hund', 'katze', 'pferd'],
        hint: 'Zähle bei jedem Tier die Beine.',
        hintDetail:
          'Ein Vogel hat zwei Beine. Ein Fisch hat keine Beine. Hund, Katze und Pferd laufen auf vier Beinen.',
        explanation: 'Hund, Katze und Pferd haben vier Beine. Das sind 3 Tiere.',
      },
      {
        id: 'a1-s3',
        interactionType: 'select-one',
        instruction: 'Was bedeutet „Markiere alle Kreise"?',
        items: [
          { id: 'o1', label: 'Ich zeige jeden Kreis.' },
          { id: 'o2', label: 'Ich zeige nur einen Kreis.' },
          { id: 'o3', label: 'Ich male das Blatt bunt an.' },
        ],
        correctAnswer: 'o1',
        hint: 'Denke an das Wort „alle".',
        hintDetail: '„Alle" bedeutet: kein Kreis wird vergessen. Also zeigst du jeden Kreis.',
        explanation: '„Markiere alle" heißt: Ich zeige jedes Ding, das passt.',
      },
    ],
    transferTask: {
      id: 'a1-t',
      interactionType: 'select-multiple',
      instruction: 'Markiere alle Zahlen, die kleiner als 10 sind.',
      items: [
        { id: 'n4', label: '4' },
        { id: 'n12', label: '12' },
        { id: 'n9', label: '9' },
        { id: 'n15', label: '15' },
        { id: 'n7', label: '7' },
      ],
      correctAnswer: ['n4', 'n9', 'n7'],
      hint: 'Kleiner als 10 heißt: Die Zahl kommt beim Zählen vor der 10.',
      hintDetail: 'Zähle: 1, 2, 3, 4 … 9, 10. Alles vor der 10 ist kleiner als 10. 12 und 15 kommen später.',
      explanation: '4, 9 und 7 kommen beim Zählen vor der 10. Sie sind kleiner als 10.',
    },
  },

  {
    id: 'a2',
    moduleId: 'A',
    skillId: 'anweisung-auswaehlen',
    title: 'Wähle aus – ich nehme genau eins',
    objective: 'Ich weiß: „Wähle aus" heißt, ich entscheide mich für genau eine Antwort.',
    story: 'Manchmal steht in der Aufgabe „Wähle aus". Dann suchst du genau eine Sache, die passt.',
    steps: [
      {
        id: 'a2-s1',
        interactionType: 'select-one',
        instruction: 'Wähle das Bild aus, auf dem genau 5 Sterne sind.',
        items: [
          { id: 'v4', label: '4 Sterne', emoji: '⭐⭐⭐⭐' },
          { id: 'v5', label: '5 Sterne', emoji: '⭐⭐⭐⭐⭐' },
          { id: 'v6', label: '6 Sterne', emoji: '⭐⭐⭐⭐⭐⭐' },
        ],
        correctAnswer: 'v5',
        hint: 'Zähle die Sterne in jeder Reihe mit dem Finger.',
        hintDetail: 'Tippe jeden Stern einmal an und zähle laut mit: 1, 2, 3, 4, 5. Nur eine Reihe endet bei 5.',
        explanation: 'Die mittlere Reihe hat 5 Sterne. Bei „wähle aus" nimmst du genau eine Antwort.',
      },
      {
        id: 'a2-s2',
        interactionType: 'select-one',
        instruction: 'Wähle den Satz aus, der zum Bild passt.',
        context: 'Auf der Wiese sind Katzen und Hunde.',
        sceneGroups: [
          { label: 'Katzen', emoji: '🐱', count: 3 },
          { label: 'Hunde', emoji: '🐶', count: 2 },
        ],
        items: [
          { id: 's1', label: 'Es sind 3 Katzen und 2 Hunde.' },
          { id: 's2', label: 'Es sind 2 Katzen und 3 Hunde.' },
          { id: 's3', label: 'Es sind 5 Hunde.' },
        ],
        correctAnswer: 's1',
        hint: 'Zähle zuerst die Katzen, dann die Hunde.',
        hintDetail: 'Oben siehst du die Katzen: 1, 2, 3. Darunter die Hunde: 1, 2. Suche den Satz mit genau diesen Zahlen.',
        explanation: '3 Katzen und 2 Hunde. Der Satz muss genau zu den gezählten Zahlen passen.',
      },
      {
        id: 'a2-s3',
        interactionType: 'select-one',
        instruction: 'In der Aufgabe steht: „Wähle eine Zahl aus, die größer als 6 ist." Welche Zahl passt?',
        items: [
          { id: 'z3', label: '3' },
          { id: 'z5', label: '5' },
          { id: 'z8', label: '8' },
        ],
        correctAnswer: 'z8',
        hint: 'Größer als 6 heißt: Die Zahl kommt nach der 6.',
        hintDetail: 'Zähle ab 6 weiter: 7, 8, 9. Diese Zahlen sind größer als 6. 3 und 5 kommen vorher.',
        explanation: '8 kommt beim Zählen nach der 6. Deshalb ist 8 größer als 6.',
      },
    ],
    transferTask: {
      id: 'a2-t',
      interactionType: 'select-one',
      instruction: 'Wähle die Frage aus, die man mit einer Zahl beantworten kann.',
      items: [
        { id: 'f1', label: 'Wie viele Kinder spielen im Garten?' },
        { id: 'f2', label: 'Magst du Fußball?' },
        { id: 'f3', label: 'Wie heißt dein Freund?' },
      ],
      correctAnswer: 'f1',
      hint: 'Auf welche Frage antwortest du mit „3" oder „7"?',
      hintDetail: 'Bei „Magst du …?" antwortest du mit Ja oder Nein. Bei „Wie heißt …?" antwortest du mit einem Namen. Nur „Wie viele …?" fragt nach einer Anzahl.',
      explanation: '„Wie viele …?" fragt nach einer Anzahl. Darauf antwortest du mit einer Zahl.',
    },
  },

  {
    id: 'a3',
    moduleId: 'A',
    skillId: 'anweisung-zuordnen',
    title: 'Ordne zu – was gehört wohin?',
    objective: 'Ich weiß: „Ordne zu" heißt, ich lege jedes Ding an den passenden Platz.',
    story: 'Bei „Ordne zu" gibt es Plätze und Dinge. Jedes Ding gehört an genau einen Platz.',
    steps: [
      {
        id: 'a3-s1',
        interactionType: 'sort-groups',
        instruction: 'Ordne zu: Obst oder Fahrzeug?',
        targets: [
          { id: 'obst', label: 'Obst' },
          { id: 'fahrzeug', label: 'Fahrzeug' },
        ],
        items: [
          { id: 'i-apfel', label: 'Apfel', emoji: '🍎' },
          { id: 'i-auto', label: 'Auto', emoji: '🚗' },
          { id: 'i-banane', label: 'Banane', emoji: '🍌' },
          { id: 'i-bus', label: 'Bus', emoji: '🚌' },
          { id: 'i-kirsche', label: 'Kirsche', emoji: '🍒' },
        ],
        correctAnswer: {
          'i-apfel': 'obst',
          'i-auto': 'fahrzeug',
          'i-banane': 'obst',
          'i-bus': 'fahrzeug',
          'i-kirsche': 'obst',
        },
        hint: 'Frage dich: Kann man das essen oder kann man damit fahren?',
        hintDetail: 'Apfel, Banane und Kirsche kann man essen – das ist Obst. Mit Auto und Bus kann man fahren – das sind Fahrzeuge.',
        explanation: 'Jedes Bild hat genau einen passenden Platz. Das ist „zuordnen".',
      },
      {
        id: 'a3-s2',
        interactionType: 'sort-groups',
        instruction: 'Ordne die Zahlen zu.',
        targets: [
          { id: 'klein', label: 'kleiner als 10' },
          { id: 'gross', label: 'größer als 10' },
        ],
        items: [
          { id: 'q4', label: '4' },
          { id: 'q13', label: '13' },
          { id: 'q8', label: '8' },
          { id: 'q17', label: '17' },
          { id: 'q2', label: '2' },
        ],
        correctAnswer: { q4: 'klein', q13: 'gross', q8: 'klein', q17: 'gross', q2: 'klein' },
        hint: 'Denke an die Zahlenreihe: Was kommt vor der 10, was danach?',
        hintDetail: '1, 2, 3, 4, 5, 6, 7, 8, 9 kommen vor der 10 – sie sind kleiner. 11, 12, 13 … kommen danach – sie sind größer.',
        explanation: '4, 8 und 2 kommen vor der 10. 13 und 17 kommen nach der 10.',
      },
      {
        id: 'a3-s3',
        interactionType: 'select-one',
        instruction: 'Was bedeutet „Ordne zu"?',
        items: [
          { id: 'z1', label: 'Ich lege jedes Ding an den passenden Platz.' },
          { id: 'z2', label: 'Ich zähle alle Dinge zusammen.' },
          { id: 'z3', label: 'Ich suche das größte Ding.' },
        ],
        correctAnswer: 'z1',
        hint: 'Beim Zuordnen bleibt kein Ding übrig.',
        hintDetail: 'Zuordnen heißt sortieren: Jedes Ding bekommt seinen Platz. Du rechnest dabei nicht.',
        explanation: '„Ordne zu" heißt sortieren: Jedes Ding kommt an seinen Platz.',
      },
    ],
    transferTask: {
      id: 'a3-t',
      interactionType: 'sort-groups',
      instruction: 'Ordne zu: Tier oder Werkzeug?',
      targets: [
        { id: 'tier', label: 'Tier' },
        { id: 'werkzeug', label: 'Werkzeug' },
      ],
      items: [
        { id: 't-hund', label: 'Hund', emoji: '🐶' },
        { id: 't-hammer', label: 'Hammer', emoji: '🔨' },
        { id: 't-katze', label: 'Katze', emoji: '🐱' },
        { id: 't-zange', label: 'Zange', emoji: '🔧' },
      ],
      correctAnswer: { 't-hund': 'tier', 't-hammer': 'werkzeug', 't-katze': 'tier', 't-zange': 'werkzeug' },
      hint: 'Lebt es, oder arbeitet man damit?',
      hintDetail: 'Ein Tier lebt und bewegt sich selbst. Ein Werkzeug nimmt man in die Hand, um etwas zu bauen oder zu reparieren.',
      explanation: 'Hund und Katze sind Tiere. Hammer und Zange sind Werkzeuge.',
    },
  },
];
