import type { Lesson } from '../types/content';

/**
 * Modul B – Dazu und weg.
 * Fokus: Die Geschichte zeigt, ob eine Menge größer oder kleiner wird.
 * Es wird bewusst KEINE Signalwort-Regel gelehrt („mehr heißt plus"),
 * sondern immer die Handlung in der Geschichte.
 */
export const moduleBLessons: Lesson[] = [
  {
    id: 'b1',
    moduleId: 'B',
    skillId: 'dazu-rechnen',
    title: 'Es kommt etwas dazu',
    objective: 'Ich erkenne in der Geschichte, dass eine Menge größer wird, und finde die passende Rechnung.',
    story: 'Auf dem Tisch liegen 5 Kekse. Papa legt 4 Kekse dazu.',
    steps: [
      {
        id: 'b1-s1',
        interactionType: 'move-objects',
        instruction: 'Lege 4 Kekse dazu auf den Tisch.',
        context: 'Auf dem Tisch liegen 5 Kekse. Papa legt 4 Kekse dazu.',
        mode: 'add',
        emoji: '🍪',
        objectLabel: 'Keks',
        startCount: 5,
        moveCount: 4,
        sourceLabel: 'Papas Teller',
        targetLabel: 'Tisch',
        correctAnswer: 4,
        hint: 'Papa legt 4 Kekse dazu. Bewege genau 4 Kekse auf den Tisch.',
        hintDetail: 'Tippe einen Keks von Papas Teller an. Er wandert auf den Tisch. Mache das viermal – dann liegen die 4 neuen Kekse beim Rest.',
        explanation: 'Die 4 Kekse kommen zu den 5 Keksen dazu. Die Menge auf dem Tisch wird größer.',
      },
      {
        id: 'b1-s2',
        interactionType: 'select-one',
        instruction: 'Welche Rechnung passt zu der Geschichte?',
        context: 'Auf dem Tisch liegen 5 Kekse. Papa legt 4 Kekse dazu.',
        items: [
          { id: 'r1', label: '5 + 4' },
          { id: 'r2', label: '5 − 4' },
          { id: 'r3', label: '4 − 5' },
        ],
        correctAnswer: 'r1',
        hint: 'Auf dem Tisch liegen jetzt mehr Kekse als vorher.',
        hintDetail: 'Am Anfang waren 5 Kekse da. Es kommen 4 dazu. Wenn eine Menge größer wird, legst du zusammen: 5 + 4.',
        explanation: 'Zwei Mengen werden zusammengelegt: 5 Kekse und 4 Kekse. Deshalb 5 + 4.',
      },
      {
        id: 'b1-s3',
        interactionType: 'number-input',
        instruction: 'Wie viele Kekse liegen jetzt auf dem Tisch?',
        context: 'Auf dem Tisch liegen 5 Kekse. Papa legt 4 Kekse dazu.',
        unit: 'Kekse',
        correctAnswer: 9,
        hint: 'Zähle von 5 weiter: 6, 7, 8 …',
        hintDetail: 'Beginne bei 5 und zähle die 4 neuen Kekse einzeln dazu: 6, 7, 8, 9. Bei 9 hörst du auf.',
        explanation: '5 + 4 = 9. Auf dem Tisch liegen jetzt 9 Kekse.',
      },
    ],
    transferTask: {
      id: 'b1-t',
      interactionType: 'number-input',
      instruction: 'Wie viele Kinder sitzen jetzt im Bus?',
      context: 'Im Bus sitzen 7 Kinder. An der Haltestelle steigen 6 Kinder ein.',
      unit: 'Kinder',
      correctAnswer: 13,
      hint: 'Steigen Kinder ein, werden es mehr oder weniger?',
      hintDetail: 'Einsteigen heißt: Die Kinder sind jetzt auch im Bus. Die Menge wird größer. Rechne 7 + 6.',
      explanation: '7 + 6 = 13. Weil Kinder einsteigen, wird die Gruppe im Bus größer.',
    },
  },

  {
    id: 'b2',
    moduleId: 'B',
    skillId: 'weg-rechnen',
    title: 'Es geht etwas weg',
    objective: 'Ich erkenne in der Geschichte, dass eine Menge kleiner wird, und finde die passende Rechnung.',
    story: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln.',
    steps: [
      {
        id: 'b2-s1',
        interactionType: 'select-one',
        instruction: 'Was sollst du herausfinden?',
        context: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln. Wie viele Murmeln hat Mina noch?',
        items: [
          { id: 'w1', label: 'Wie viele Murmeln Mina noch hat.' },
          { id: 'w2', label: 'Wie viele Murmeln Ben vorher hatte.' },
          { id: 'w3', label: 'Wie viele Murmeln zusammen 10 sind.' },
        ],
        correctAnswer: 'w1',
        hint: 'Lies die Frage am Ende der Geschichte noch einmal.',
        hintDetail: 'Die Frage lautet: „Wie viele Murmeln hat Mina noch?" Gesucht ist also Minas Anzahl nach dem Verschenken.',
        explanation: 'Gesucht ist Minas Rest. Vorher zu wissen, was gefragt ist, macht das Rechnen leichter.',
      },
      {
        id: 'b2-s2',
        interactionType: 'move-objects',
        instruction: 'Gib Ben 3 Murmeln.',
        context: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln.',
        mode: 'remove',
        emoji: '🔵',
        objectLabel: 'Murmel',
        startCount: 8,
        moveCount: 3,
        sourceLabel: 'Mina',
        targetLabel: 'Ben',
        correctAnswer: 3,
        hint: 'Bewege genau 3 Murmeln von Mina zu Ben.',
        hintDetail: 'Tippe eine Murmel bei Mina an – sie wandert zu Ben. Mache das dreimal. Bei Mina bleibt der Rest liegen.',
        explanation: 'Von Minas 8 Murmeln gehen 3 weg. Ihre Menge wird kleiner.',
      },
      {
        id: 'b2-s3',
        interactionType: 'select-one',
        instruction: 'Welche Rechnung passt?',
        context: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln.',
        items: [
          { id: 'p1', label: '8 − 3' },
          { id: 'p2', label: '8 + 3' },
          { id: 'p3', label: '3 + 3' },
        ],
        correctAnswer: 'p1',
        hint: 'Mina hat am Ende weniger Murmeln als am Anfang.',
        hintDetail: 'Mina startet mit 8. Sie gibt 3 weg. Wenn etwas weggeht, nimmst du weg: 8 − 3.',
        explanation: 'Von der Menge 8 wird 3 weggenommen: 8 − 3.',
      },
      {
        id: 'b2-s4',
        interactionType: 'number-input',
        instruction: 'Wie viele Murmeln hat Mina noch?',
        context: 'Mina hat 8 Murmeln. Sie gibt Ben 3 Murmeln.',
        unit: 'Murmeln',
        correctAnswer: 5,
        hint: 'Zähle von 8 rückwärts: 7, 6 …',
        hintDetail: 'Nimm die 3 weggegebenen Murmeln einzeln weg: 8 → 7 → 6 → 5. Es bleiben 5 Murmeln bei Mina.',
        explanation: '8 − 3 = 5. Bei Mina bleiben 5 Murmeln liegen.',
      },
    ],
    transferTask: {
      id: 'b2-t',
      interactionType: 'number-input',
      instruction: 'Wie viele Trauben liegen noch auf dem Teller?',
      context: 'Auf dem Teller liegen 12 Trauben. Lea isst 4 Trauben.',
      unit: 'Trauben',
      correctAnswer: 8,
      hint: 'Gegessene Trauben liegen nicht mehr auf dem Teller.',
      hintDetail: 'Von 12 Trauben gehen 4 weg. Zähle rückwärts: 11, 10, 9, 8. Oder rechne 12 − 4.',
      explanation: '12 − 4 = 8. Weil Lea Trauben isst, wird die Menge auf dem Teller kleiner.',
    },
  },

  {
    id: 'b3',
    moduleId: 'B',
    skillId: 'dazu-oder-weg',
    title: 'Wird es mehr oder weniger?',
    objective: 'Ich entscheide anhand der Geschichte, ob eine Menge größer oder kleiner wird.',
    story: 'Nicht das einzelne Wort entscheidet, sondern was in der Geschichte passiert.',
    steps: [
      {
        id: 'b3-s1',
        interactionType: 'select-one',
        instruction: 'Wird es mehr oder weniger?',
        context: 'Tom hat 6 Sticker. Lisa schenkt ihm 5 Sticker.',
        items: [
          { id: 'm1', label: 'Tom hat jetzt mehr Sticker.' },
          { id: 'm2', label: 'Tom hat jetzt weniger Sticker.' },
          { id: 'm3', label: 'Tom hat gleich viele Sticker.' },
        ],
        correctAnswer: 'm1',
        hint: 'Tom bekommt etwas dazu. Was passiert dann mit seiner Menge?',
        hintDetail: 'Schenken heißt: Lisa gibt, Tom bekommt. Toms Stapel wächst also.',
        explanation: 'Tom bekommt Sticker dazu. Seine Menge wird größer.',
      },
      {
        id: 'b3-s2',
        interactionType: 'select-one',
        instruction: 'Welche Rechnung passt?',
        context: 'Sara hat 14 Karten. Sie verschenkt 5 Karten.',
        items: [
          { id: 'k1', label: '14 − 5' },
          { id: 'k2', label: '14 + 5' },
          { id: 'k3', label: '5 + 5' },
        ],
        correctAnswer: 'k1',
        hint: 'Sara gibt Karten weg. Hat sie danach mehr oder weniger?',
        hintDetail: 'Verschenken heißt: Die Karten sind weg. Saras Menge wird kleiner, also 14 − 5.',
        explanation: 'Von Saras 14 Karten gehen 5 weg: 14 − 5.',
      },
      {
        id: 'b3-s3',
        interactionType: 'number-input',
        instruction: 'Wie viele Karten hat Sara noch?',
        context: 'Sara hat 14 Karten. Sie verschenkt 5 Karten.',
        unit: 'Karten',
        correctAnswer: 9,
        hint: 'Zähle von 14 rückwärts.',
        hintDetail: 'Nimm die 5 Karten einzeln weg: 13, 12, 11, 10, 9. Es bleiben 9 Karten.',
        explanation: '14 − 5 = 9. Sara behält 9 Karten.',
      },
    ],
    transferTask: {
      id: 'b3-t',
      interactionType: 'number-input',
      instruction: 'Wie viele Äpfel liegen noch im Korb?',
      context: 'Im Korb liegen 15 Äpfel. Oma nimmt 6 Äpfel heraus.',
      unit: 'Äpfel',
      correctAnswer: 9,
      hint: 'Herausnehmen heißt: Die Äpfel sind nicht mehr im Korb.',
      hintDetail: 'Der Korb hat 15 Äpfel. 6 gehen heraus. Die Menge im Korb wird kleiner: 15 − 6.',
      explanation: '15 − 6 = 9. Im Korb bleiben 9 Äpfel.',
    },
  },
];
