import type { Lesson } from '../types/content';

/**
 * Modul A – Arbeitsanweisungen verstehen.
 * Fokus: Was verlangt das Wort in der Aufgabe von mir? (markieren / auswählen / zuordnen)
 */
export const moduleALessons: Lesson[] = [
  {
    id: 'a1',
    moduleId: 'A',
    skillId: 'anweisung-markieren',
    titleDe: 'Markiere – ich zeige alle',
    objectiveDe: 'Ich weiß: „Markiere" heißt, ich zeige jedes Ding, das passt – nicht nur eines.',
    storyDe: 'In Aufgaben steht oft das Wort „markiere". Das heißt: Du zeigst jedes Ding, das zu der Frage passt.',
    steps: [
      {
        id: 'a1-s1',
        interactionType: 'select-multiple',
        instructionDe: 'Markiere alle Äpfel.',
        items: [
          { id: 'ap1', labelDe: 'Apfel', emoji: '🍎' },
          { id: 'bi1', labelDe: 'Birne', emoji: '🍐' },
          { id: 'ap2', labelDe: 'Apfel', emoji: '🍎' },
          { id: 'ba1', labelDe: 'Banane', emoji: '🍌' },
          { id: 'ap3', labelDe: 'Apfel', emoji: '🍎' },
          { id: 'bi2', labelDe: 'Birne', emoji: '🍐' },
        ],
        correctAnswer: ['ap1', 'ap2', 'ap3'],
        hintDe: 'Es ist mehr als ein Apfel dabei. Schau jedes Bild einzeln an.',
        hintDetailDe:
          'Gehe von links nach rechts. Frage dich bei jedem Bild: Ist das ein Apfel? Wenn ja, tippe es an. Am Ende sind alle Äpfel markiert.',
        hintTr: '„Markieren" = işaretlemek. Uygun olan HER şeyi işaretlemelisin, sadece bir tanesini değil.',
        explanationDe: 'Es sind 3 Äpfel. Bei „markiere" zeigst du immer alle passenden Dinge.',
        explanationTr: 'Toplam 3 elma var. „Markiere" dediğinde uygun olan hepsini işaretlersin.',
      },
      {
        id: 'a1-s2',
        interactionType: 'select-multiple',
        instructionDe: 'Markiere alle Tiere, die vier Beine haben.',
        items: [
          { id: 'hund', labelDe: 'Hund', emoji: '🐶' },
          { id: 'vogel', labelDe: 'Vogel', emoji: '🐦' },
          { id: 'katze', labelDe: 'Katze', emoji: '🐱' },
          { id: 'fisch', labelDe: 'Fisch', emoji: '🐟' },
          { id: 'pferd', labelDe: 'Pferd', emoji: '🐴' },
        ],
        correctAnswer: ['hund', 'katze', 'pferd'],
        hintDe: 'Zähle bei jedem Tier die Beine.',
        hintDetailDe:
          'Ein Vogel hat zwei Beine. Ein Fisch hat keine Beine. Hund, Katze und Pferd laufen auf vier Beinen.',
        hintTr: 'Her hayvanın bacaklarını say. Kuşun 2, balığın 0 bacağı var.',
        explanationDe: 'Hund, Katze und Pferd haben vier Beine. Das sind 3 Tiere.',
        explanationTr: 'Köpek, kedi ve atın dört bacağı var. Yani 3 hayvan.',
      },
      {
        id: 'a1-s3',
        interactionType: 'select-one',
        instructionDe: 'Was bedeutet „Markiere alle Kreise"?',
        items: [
          { id: 'o1', labelDe: 'Ich zeige jeden Kreis.' },
          { id: 'o2', labelDe: 'Ich zeige nur einen Kreis.' },
          { id: 'o3', labelDe: 'Ich male das Blatt bunt an.' },
        ],
        correctAnswer: 'o1',
        hintDe: 'Denke an das Wort „alle".',
        hintDetailDe: '„Alle" bedeutet: kein Kreis wird vergessen. Also zeigst du jeden Kreis.',
        hintTr: '„Alle" = hepsi. Yani hiçbir daireyi atlamadan hepsini gösterirsin.',
        explanationDe: '„Markiere alle" heißt: Ich zeige jedes Ding, das passt.',
        explanationTr: '„Markiere alle" = uygun olan her şeyi göster demektir.',
      },
    ],
    transferTask: {
      id: 'a1-t',
      interactionType: 'select-multiple',
      instructionDe: 'Markiere alle Zahlen, die kleiner als 10 sind.',
      items: [
        { id: 'n4', labelDe: '4' },
        { id: 'n12', labelDe: '12' },
        { id: 'n9', labelDe: '9' },
        { id: 'n15', labelDe: '15' },
        { id: 'n7', labelDe: '7' },
      ],
      correctAnswer: ['n4', 'n9', 'n7'],
      hintDe: 'Kleiner als 10 heißt: Die Zahl kommt beim Zählen vor der 10.',
      hintDetailDe: 'Zähle: 1, 2, 3, 4 … 9, 10. Alles vor der 10 ist kleiner als 10. 12 und 15 kommen später.',
      hintTr: '10’dan küçük demek: sayarken 10’dan önce gelen sayılar. 12 ve 15 sonra gelir.',
      explanationDe: '4, 9 und 7 kommen beim Zählen vor der 10. Sie sind kleiner als 10.',
      explanationTr: '4, 9 ve 7 sayarken 10’dan önce gelir, yani 10’dan küçüktür.',
    },
  },

  {
    id: 'a2',
    moduleId: 'A',
    skillId: 'anweisung-auswaehlen',
    titleDe: 'Wähle aus – ich nehme genau eins',
    objectiveDe: 'Ich weiß: „Wähle aus" heißt, ich entscheide mich für genau eine Antwort.',
    storyDe: 'Manchmal steht in der Aufgabe „Wähle aus". Dann suchst du genau eine Sache, die passt.',
    steps: [
      {
        id: 'a2-s1',
        interactionType: 'select-one',
        instructionDe: 'Wähle das Bild aus, auf dem genau 5 Sterne sind.',
        items: [
          { id: 'v4', labelDe: '4 Sterne', emoji: '⭐⭐⭐⭐' },
          { id: 'v5', labelDe: '5 Sterne', emoji: '⭐⭐⭐⭐⭐' },
          { id: 'v6', labelDe: '6 Sterne', emoji: '⭐⭐⭐⭐⭐⭐' },
        ],
        correctAnswer: 'v5',
        hintDe: 'Zähle die Sterne in jeder Reihe mit dem Finger.',
        hintDetailDe: 'Tippe jeden Stern einmal an und zähle laut mit: 1, 2, 3, 4, 5. Nur eine Reihe endet bei 5.',
        hintTr: 'Her sıradaki yıldızları parmağınla sayarak kontrol et: 1, 2, 3, 4, 5.',
        explanationDe: 'Die mittlere Reihe hat 5 Sterne. Bei „wähle aus" nimmst du genau eine Antwort.',
        explanationTr: 'Ortadaki sırada 5 yıldız var. „Wähle aus" dediğinde tek bir cevap seçersin.',
      },
      {
        id: 'a2-s2',
        interactionType: 'select-one',
        instructionDe: 'Wähle den Satz aus, der zum Bild passt.',
        contextDe: 'Auf der Wiese sind Katzen und Hunde.',
        sceneGroups: [
          { labelDe: 'Katzen', emoji: '🐱', count: 3 },
          { labelDe: 'Hunde', emoji: '🐶', count: 2 },
        ],
        items: [
          { id: 's1', labelDe: 'Es sind 3 Katzen und 2 Hunde.' },
          { id: 's2', labelDe: 'Es sind 2 Katzen und 3 Hunde.' },
          { id: 's3', labelDe: 'Es sind 5 Hunde.' },
        ],
        correctAnswer: 's1',
        hintDe: 'Zähle zuerst die Katzen, dann die Hunde.',
        hintDetailDe: 'Oben siehst du die Katzen: 1, 2, 3. Darunter die Hunde: 1, 2. Suche den Satz mit genau diesen Zahlen.',
        hintTr: 'Önce kedileri say (3), sonra köpekleri say (2). Bu iki sayının geçtiği cümleyi seç.',
        explanationDe: '3 Katzen und 2 Hunde. Der Satz muss genau zu den gezählten Zahlen passen.',
        explanationTr: '3 kedi ve 2 köpek var. Cümledeki sayılar saydığın sayılarla aynı olmalı.',
      },
      {
        id: 'a2-s3',
        interactionType: 'select-one',
        instructionDe: 'In der Aufgabe steht: „Wähle eine Zahl aus, die größer als 6 ist." Welche Zahl passt?',
        items: [
          { id: 'z3', labelDe: '3' },
          { id: 'z5', labelDe: '5' },
          { id: 'z8', labelDe: '8' },
        ],
        correctAnswer: 'z8',
        hintDe: 'Größer als 6 heißt: Die Zahl kommt nach der 6.',
        hintDetailDe: 'Zähle ab 6 weiter: 7, 8, 9. Diese Zahlen sind größer als 6. 3 und 5 kommen vorher.',
        hintTr: '6’dan büyük = sayarken 6’dan sonra gelen sayı. 7, 8, 9 gibi.',
        explanationDe: '8 kommt beim Zählen nach der 6. Deshalb ist 8 größer als 6.',
        explanationTr: '8 sayarken 6’dan sonra gelir, bu yüzden 6’dan büyüktür.',
      },
    ],
    transferTask: {
      id: 'a2-t',
      interactionType: 'select-one',
      instructionDe: 'Wähle die Frage aus, die man mit einer Zahl beantworten kann.',
      items: [
        { id: 'f1', labelDe: 'Wie viele Kinder spielen im Garten?' },
        { id: 'f2', labelDe: 'Magst du Fußball?' },
        { id: 'f3', labelDe: 'Wie heißt dein Freund?' },
      ],
      correctAnswer: 'f1',
      hintDe: 'Auf welche Frage antwortest du mit „3" oder „7"?',
      hintDetailDe: 'Bei „Magst du …?" antwortest du mit Ja oder Nein. Bei „Wie heißt …?" antwortest du mit einem Namen. Nur „Wie viele …?" fragt nach einer Anzahl.',
      hintTr: 'Hangi soruya „3" veya „7" diye cevap verirsin? „Wie viele" = kaç tane, sayı ister.',
      explanationDe: '„Wie viele …?" fragt nach einer Anzahl. Darauf antwortest du mit einer Zahl.',
      explanationTr: '„Wie viele …?" adet sorar, cevabı bir sayıdır.',
    },
  },

  {
    id: 'a3',
    moduleId: 'A',
    skillId: 'anweisung-zuordnen',
    titleDe: 'Ordne zu – was gehört wohin?',
    objectiveDe: 'Ich weiß: „Ordne zu" heißt, ich lege jedes Ding an den passenden Platz.',
    storyDe: 'Bei „Ordne zu" gibt es Plätze und Dinge. Jedes Ding gehört an genau einen Platz.',
    steps: [
      {
        id: 'a3-s1',
        interactionType: 'sort-groups',
        instructionDe: 'Ordne zu: Obst oder Fahrzeug?',
        targets: [
          { id: 'obst', labelDe: 'Obst' },
          { id: 'fahrzeug', labelDe: 'Fahrzeug' },
        ],
        items: [
          { id: 'i-apfel', labelDe: 'Apfel', emoji: '🍎' },
          { id: 'i-auto', labelDe: 'Auto', emoji: '🚗' },
          { id: 'i-banane', labelDe: 'Banane', emoji: '🍌' },
          { id: 'i-bus', labelDe: 'Bus', emoji: '🚌' },
          { id: 'i-kirsche', labelDe: 'Kirsche', emoji: '🍒' },
        ],
        correctAnswer: {
          'i-apfel': 'obst',
          'i-auto': 'fahrzeug',
          'i-banane': 'obst',
          'i-bus': 'fahrzeug',
          'i-kirsche': 'obst',
        },
        hintDe: 'Frage dich: Kann man das essen oder kann man damit fahren?',
        hintDetailDe: 'Apfel, Banane und Kirsche kann man essen – das ist Obst. Mit Auto und Bus kann man fahren – das sind Fahrzeuge.',
        hintTr: 'Kendine sor: Bu yenir mi, yoksa binilir mi? Yeniyorsa Obst, biniliyorsa Fahrzeug.',
        explanationDe: 'Jedes Bild hat genau einen passenden Platz. Das ist „zuordnen".',
        explanationTr: 'Her resmin tam bir yeri var. „Zuordnen" = eşleştirmek.',
      },
      {
        id: 'a3-s2',
        interactionType: 'sort-groups',
        instructionDe: 'Ordne die Zahlen zu.',
        targets: [
          { id: 'klein', labelDe: 'kleiner als 10' },
          { id: 'gross', labelDe: 'größer als 10' },
        ],
        items: [
          { id: 'q4', labelDe: '4' },
          { id: 'q13', labelDe: '13' },
          { id: 'q8', labelDe: '8' },
          { id: 'q17', labelDe: '17' },
          { id: 'q2', labelDe: '2' },
        ],
        correctAnswer: { q4: 'klein', q13: 'gross', q8: 'klein', q17: 'gross', q2: 'klein' },
        hintDe: 'Denke an die Zahlenreihe: Was kommt vor der 10, was danach?',
        hintDetailDe: '1, 2, 3, 4, 5, 6, 7, 8, 9 kommen vor der 10 – sie sind kleiner. 11, 12, 13 … kommen danach – sie sind größer.',
        hintTr: 'Sayı doğrusunu düşün: 10’dan önce gelenler küçük, sonra gelenler büyük.',
        explanationDe: '4, 8 und 2 kommen vor der 10. 13 und 17 kommen nach der 10.',
        explanationTr: '4, 8 ve 2 → 10’dan önce. 13 ve 17 → 10’dan sonra.',
      },
      {
        id: 'a3-s3',
        interactionType: 'select-one',
        instructionDe: 'Was bedeutet „Ordne zu"?',
        items: [
          { id: 'z1', labelDe: 'Ich lege jedes Ding an den passenden Platz.' },
          { id: 'z2', labelDe: 'Ich zähle alle Dinge zusammen.' },
          { id: 'z3', labelDe: 'Ich suche das größte Ding.' },
        ],
        correctAnswer: 'z1',
        hintDe: 'Beim Zuordnen bleibt kein Ding übrig.',
        hintDetailDe: 'Zuordnen heißt sortieren: Jedes Ding bekommt seinen Platz. Du rechnest dabei nicht.',
        hintTr: '„Zuordnen" = her şeyi ait olduğu yere koymak. Hesap yapmazsın.',
        explanationDe: '„Ordne zu" heißt sortieren: Jedes Ding kommt an seinen Platz.',
        explanationTr: '„Ordne zu" = sınıflandır, her şeyi yerine koy.',
      },
    ],
    transferTask: {
      id: 'a3-t',
      interactionType: 'sort-groups',
      instructionDe: 'Ordne zu: Tier oder Werkzeug?',
      targets: [
        { id: 'tier', labelDe: 'Tier' },
        { id: 'werkzeug', labelDe: 'Werkzeug' },
      ],
      items: [
        { id: 't-hund', labelDe: 'Hund', emoji: '🐶' },
        { id: 't-hammer', labelDe: 'Hammer', emoji: '🔨' },
        { id: 't-katze', labelDe: 'Katze', emoji: '🐱' },
        { id: 't-zange', labelDe: 'Zange', emoji: '🔧' },
      ],
      correctAnswer: { 't-hund': 'tier', 't-hammer': 'werkzeug', 't-katze': 'tier', 't-zange': 'werkzeug' },
      hintDe: 'Lebt es, oder arbeitet man damit?',
      hintDetailDe: 'Ein Tier lebt und bewegt sich selbst. Ein Werkzeug nimmt man in die Hand, um etwas zu bauen oder zu reparieren.',
      hintTr: 'Canlı mı, yoksa onunla çalışılan bir alet mi?',
      explanationDe: 'Hund und Katze sind Tiere. Hammer und Zange sind Werkzeuge.',
      explanationTr: 'Köpek ve kedi hayvan; çekiç ve pense alettir.',
    },
  },
];
