import type { Lesson } from '../types/content';

/**
 * Modul D – Was ist in der Aufgabe gefragt?
 * Fokus: gesuchte Information erkennen, nötige Zahlen auswählen (mit Ablenkzahlen),
 * passendes bildliches Modell zur Frage wählen.
 */
export const moduleDLessons: Lesson[] = [
  {
    id: 'd1',
    moduleId: 'D',
    skillId: 'frage-erkennen',
    titleDe: 'Was will die Frage wissen?',
    objectiveDe: 'Ich lese die Frage genau und sage, welche Information gesucht ist.',
    storyDe: 'Paul sammelt Steine. Am Montag findet er 7 Steine. Am Dienstag findet er 5 Steine.',
    steps: [
      {
        id: 'd1-s1',
        interactionType: 'select-one',
        instructionDe: 'Die Frage lautet: „Wie viele Steine hat Paul zusammen?" Was sollst du herausfinden?',
        contextDe: 'Paul findet am Montag 7 Steine und am Dienstag 5 Steine.',
        items: [
          { id: 'f1', labelDe: 'Die Anzahl aller Steine von Montag und Dienstag.' },
          { id: 'f2', labelDe: 'Wie viele Steine er nur am Montag gefunden hat.' },
          { id: 'f3', labelDe: 'An welchem Tag er mehr gefunden hat.' },
        ],
        correctAnswer: 'f1',
        hintDe: 'Achte auf das Wort „zusammen".',
        hintDetailDe: '„Zusammen" heißt: beide Tage in einer Menge. Du legst die Steine von Montag und Dienstag in einen Haufen.',
        hintTr: '„Zusammen" = toplam. İki günün taşlarını tek bir yığında topluyorsun.',
        explanationDe: 'Gesucht ist die Gesamtzahl aus beiden Tagen.',
        explanationTr: 'Aranan, iki günün toplam sayısı.',
      },
      {
        id: 'd1-s2',
        interactionType: 'number-input',
        instructionDe: 'Wie viele Steine hat Paul zusammen?',
        contextDe: 'Montag: 7 Steine. Dienstag: 5 Steine.',
        unitDe: 'Steine',
        correctAnswer: 12,
        hintDe: 'Lege beide Mengen zusammen.',
        hintDetailDe: 'Beginne bei 7 und zähle die 5 Steine vom Dienstag dazu: 8, 9, 10, 11, 12.',
        hintTr: '7’den devam et ve 5 tane say: 8, 9, 10, 11, 12.',
        explanationDe: '7 + 5 = 12. Beide Haufen zusammen sind 12 Steine.',
        explanationTr: '7 + 5 = 12. İki yığın birlikte 12 taş.',
      },
      {
        id: 'd1-s3',
        interactionType: 'select-one',
        instructionDe: 'Jetzt lautet die Frage: „An welchem Tag hat Paul mehr Steine gefunden?" Was ist die Antwort?',
        contextDe: 'Montag: 7 Steine. Dienstag: 5 Steine.',
        sceneGroups: [
          { labelDe: 'Montag', emoji: '🪨', count: 7 },
          { labelDe: 'Dienstag', emoji: '🪨', count: 5 },
        ],
        items: [
          { id: 'g1', labelDe: 'Am Montag.' },
          { id: 'g2', labelDe: 'Am Dienstag.' },
          { id: 'g3', labelDe: 'An beiden Tagen gleich viel.' },
        ],
        correctAnswer: 'g1',
        hintDe: 'Diese Frage will keine Summe, sondern einen Vergleich.',
        hintDetailDe: 'Vergleiche 7 und 5. Die größere Zahl gehört zum Tag mit mehr Steinen.',
        hintTr: 'Bu soru toplam istemiyor, karşılaştırma istiyor. 7 ile 5’i karşılaştır.',
        explanationDe: '7 ist größer als 5. Dieselbe Geschichte kann verschiedene Fragen haben.',
        explanationTr: '7 > 5. Aynı hikâyeye farklı sorular sorulabilir.',
      },
    ],
    transferTask: {
      id: 'd1-t',
      interactionType: 'select-one',
      instructionDe: 'Was sollst du herausfinden?',
      contextDe: 'Nina hat 9 Luftballons. 4 Luftballons platzen. Frage: Wie viele Luftballons hat Nina noch?',
      items: [
        { id: 'h1', labelDe: 'Wie viele Luftballons übrig sind.' },
        { id: 'h2', labelDe: 'Wie viele Luftballons geplatzt sind.' },
        { id: 'h3', labelDe: 'Wie viele Luftballons Nina gekauft hat.' },
      ],
      correctAnswer: 'h1',
      hintDe: 'Achte auf das Wort „noch".',
      hintDetailDe: '„Noch" fragt nach dem Rest: Was ist am Ende übrig? Die Zahl 4 steht schon in der Geschichte.',
      hintTr: '„Noch" = geriye kalan. Yani sonunda elde kalan sayı soruluyor.',
      explanationDe: 'Gesucht ist der Rest nach dem Platzen, nicht die Zahl aus der Geschichte.',
      explanationTr: 'Aranan, patladıktan sonra kalan sayı; hikâyede zaten yazan sayı değil.',
    },
  },

  {
    id: 'd2',
    moduleId: 'D',
    skillId: 'zahlen-auswaehlen',
    titleDe: 'Welche Zahlen brauche ich?',
    objectiveDe: 'Ich erkenne, welche Zahlen zur Frage gehören – und welche ich nicht brauche.',
    storyDe: 'In Aufgaben stehen manchmal Zahlen, die man für die Rechnung gar nicht braucht.',
    steps: [
      {
        id: 'd2-s1',
        interactionType: 'select-multiple',
        instructionDe: 'Markiere die Zahlen, die du für die Rechnung brauchst.',
        contextDe: 'Lisa ist 8 Jahre alt. Sie hat 6 Bücher. Sie kauft 3 Bücher dazu. Frage: Wie viele Bücher hat Lisa jetzt?',
        items: [
          { id: 'j8', labelDe: '8 Jahre' },
          { id: 'b6', labelDe: '6 Bücher' },
          { id: 'b3', labelDe: '3 Bücher' },
        ],
        correctAnswer: ['b6', 'b3'],
        hintDe: 'Die Frage geht um Bücher, nicht um das Alter.',
        hintDetailDe: 'Lies die Frage: „Wie viele Bücher hat Lisa jetzt?" Nur Zahlen, die Bücher zählen, gehören zur Rechnung. Das Alter ändert die Bücherzahl nicht.',
        hintTr: 'Soru kitapları soruyor, yaşı değil. Sadece kitapla ilgili sayıları işaretle.',
        explanationDe: 'Gesucht sind Bücher, also brauchst du 6 und 3. Die 8 Jahre gehören nicht zur Rechnung.',
        explanationTr: 'Kitap soruluyor, o yüzden 6 ve 3 gerekli. 8 yaş hesaba girmez.',
      },
      {
        id: 'd2-s2',
        interactionType: 'select-one',
        instructionDe: 'Welche Rechnung passt?',
        contextDe: 'Lisa hat 6 Bücher und kauft 3 Bücher dazu.',
        items: [
          { id: 'r1', labelDe: '6 + 3' },
          { id: 'r2', labelDe: '8 + 6' },
          { id: 'r3', labelDe: '8 − 3' },
        ],
        correctAnswer: 'r1',
        hintDe: 'Benutze nur die Zahlen, die Bücher zählen.',
        hintDetailDe: 'Lisa hat 6 Bücher. Sie kauft 3 dazu, also wird ihre Menge größer: 6 + 3.',
        hintTr: 'Sadece kitap sayıları kullanılır: 6 + 3.',
        explanationDe: 'Zu den 6 Büchern kommen 3 dazu: 6 + 3.',
        explanationTr: '6 kitabın üzerine 3 ekleniyor: 6 + 3.',
      },
      {
        id: 'd2-s3',
        interactionType: 'number-input',
        instructionDe: 'Wie viele Bücher hat Lisa jetzt?',
        contextDe: 'Lisa hat 6 Bücher und kauft 3 Bücher dazu.',
        unitDe: 'Bücher',
        correctAnswer: 9,
        hintDe: 'Zähle von 6 weiter.',
        hintDetailDe: 'Beginne bei 6 und zähle 3 dazu: 7, 8, 9.',
        hintTr: '6’dan devam et: 7, 8, 9.',
        explanationDe: '6 + 3 = 9. Lisa hat jetzt 9 Bücher.',
        explanationTr: '6 + 3 = 9. Lisa’nın şimdi 9 kitabı var.',
      },
    ],
    transferTask: {
      id: 'd2-t',
      interactionType: 'select-multiple',
      instructionDe: 'Markiere die Zahlen, die du für die Rechnung brauchst.',
      contextDe: 'Tom hat 4 Freunde eingeladen. Er ist 9 Jahre alt. Auf dem Tisch liegen 15 Muffins. Die Kinder essen 6 Muffins. Frage: Wie viele Muffins liegen noch auf dem Tisch?',
      items: [
        { id: 'z4', labelDe: '4 Freunde' },
        { id: 'z9', labelDe: '9 Jahre' },
        { id: 'z15', labelDe: '15 Muffins' },
        { id: 'z6', labelDe: '6 Muffins' },
      ],
      correctAnswer: ['z15', 'z6'],
      hintDe: 'Wonach fragt die Aufgabe – nach Muffins oder nach Kindern?',
      hintDetailDe: 'Gefragt sind Muffins auf dem Tisch. Nur Zahlen, die Muffins zählen, gehören zur Rechnung: 15 und 6.',
      hintTr: 'Soru muffin soruyor. Sadece muffin sayıları gerekli: 15 ve 6.',
      explanationDe: 'Es gehören 15 und 6 zur Rechnung. Freunde und Alter ändern die Muffinzahl nicht.',
      explanationTr: 'Hesaba 15 ve 6 girer. Arkadaş sayısı ve yaş muffin sayısını değiştirmez.',
    },
  },

  {
    id: 'd3',
    moduleId: 'D',
    skillId: 'modell-waehlen',
    titleDe: 'Welches Bild passt zur Frage?',
    objectiveDe: 'Ich wähle das passende Bild-Modell: zusammenlegen, wegnehmen oder vergleichen.',
    storyDe: 'Zu jeder Frage passt ein Bild: zusammenlegen, wegnehmen oder zwei Mengen vergleichen.',
    steps: [
      {
        id: 'd3-s1',
        interactionType: 'select-one',
        instructionDe: 'Welches Bild passt zur Frage?',
        contextDe: 'Anna hat 5 Stifte. Sie bekommt 4 Stifte dazu. Wie viele Stifte hat sie jetzt?',
        items: [
          { id: 'm1', labelDe: 'Zwei Gruppen werden zusammengelegt.', emoji: '🟢🟢🟢🟢🟢 ➕ 🟢🟢🟢🟢' },
          { id: 'm2', labelDe: 'Von einer Gruppe wird etwas weggenommen.', emoji: '🟢🟢🟢🟢🟢 ➖' },
          { id: 'm3', labelDe: 'Zwei Gruppen werden nebeneinander verglichen.', emoji: '🟢🟢🟢 ↔ 🔵🔵' },
        ],
        correctAnswer: 'm1',
        hintDe: 'Anna bekommt Stifte dazu. Wird ihre Menge größer oder kleiner?',
        hintDetailDe: 'Dazubekommen heißt: Eine zweite Gruppe kommt zur ersten. Beide zusammen ergeben die neue Menge.',
        hintTr: 'Anna kalem alıyor, yani ikinci grup birinciye ekleniyor.',
        explanationDe: 'Beim Dazubekommen legst du zwei Gruppen zusammen.',
        explanationTr: 'Bir şey eklenince iki grubu birleştirirsin.',
      },
      {
        id: 'd3-s2',
        interactionType: 'select-one',
        instructionDe: 'Welches Bild passt zur Frage?',
        contextDe: 'In Klasse A sind 14 Kinder, in Klasse B sind 11 Kinder. Wie viele Kinder mehr sind in Klasse A?',
        items: [
          { id: 'n1', labelDe: 'Zwei Gruppen werden nebeneinander verglichen.', emoji: '🟦🟦🟦 ↔ 🟧🟧' },
          { id: 'n2', labelDe: 'Zwei Gruppen werden zusammengelegt.', emoji: '🟦🟦🟦 ➕ 🟧🟧' },
          { id: 'n3', labelDe: 'Von einer Gruppe wird etwas weggenommen.', emoji: '🟦🟦🟦 ➖' },
        ],
        correctAnswer: 'n1',
        hintDe: '„Wie viele mehr" fragt nach dem Unterschied.',
        hintDetailDe: 'Die Kinder gehen nicht weg und kommen nicht dazu. Beide Klassen bleiben. Du legst die Reihen nebeneinander und schaust, was übrig bleibt.',
        hintTr: '„Wie viele mehr" farkı sorar. Gruplar yan yana konur, artan sayılır.',
        explanationDe: 'Beim Vergleichen bleiben beide Mengen bestehen. Gesucht ist der Unterschied.',
        explanationTr: 'Karşılaştırmada iki grup da durur; aranan aradaki farktır.',
      },
      {
        id: 'd3-s3',
        interactionType: 'select-one',
        instructionDe: 'Welches Bild passt zur Frage?',
        contextDe: 'Von 12 Keksen isst Ben 5 Kekse. Wie viele Kekse bleiben?',
        items: [
          { id: 'o1', labelDe: 'Von einer Gruppe wird etwas weggenommen.', emoji: '🍪🍪🍪🍪 ➖ 🍪🍪' },
          { id: 'o2', labelDe: 'Zwei Gruppen werden zusammengelegt.', emoji: '🍪🍪 ➕ 🍪🍪' },
          { id: 'o3', labelDe: 'Zwei Gruppen werden nebeneinander verglichen.', emoji: '🍪🍪🍪 ↔ 🍪' },
        ],
        correctAnswer: 'o1',
        hintDe: 'Gegessene Kekse sind nicht mehr da.',
        hintDetailDe: 'Es gibt nur eine Gruppe: die 12 Kekse. Davon verschwinden 5. Die Gruppe wird kleiner.',
        hintTr: 'Tek bir grup var (12 kurabiye) ve 5’i gidiyor. Grup küçülüyor.',
        explanationDe: 'Beim Wegnehmen bleibt ein Rest von einer einzigen Gruppe.',
        explanationTr: 'Çıkarmada tek gruptan kalan miktar bulunur.',
      },
    ],
    transferTask: {
      id: 'd3-t',
      interactionType: 'select-one',
      instructionDe: 'Welches Bild passt zur Frage?',
      contextDe: 'Im Regal stehen 7 rote und 6 blaue Tassen. Wie viele Tassen sind es zusammen?',
      items: [
        { id: 'p1', labelDe: 'Zwei Gruppen werden zusammengelegt.', emoji: '🔴🔴🔴 ➕ 🔵🔵🔵' },
        { id: 'p2', labelDe: 'Von einer Gruppe wird etwas weggenommen.', emoji: '🔴🔴🔴 ➖' },
        { id: 'p3', labelDe: 'Zwei Gruppen werden nebeneinander verglichen.', emoji: '🔴🔴🔴 ↔ 🔵🔵' },
      ],
      correctAnswer: 'p1',
      hintDe: 'Achte auf das Wort „zusammen".',
      hintDetailDe: 'Die roten und die blauen Tassen stehen im selben Regal. Für die Gesamtzahl legst du beide Gruppen zusammen.',
      hintTr: '„Zusammen" = toplam. Kırmızı ve mavi fincanları birleştirirsin.',
      explanationDe: 'Bei „zusammen" bildest du aus zwei Gruppen eine große Menge.',
      explanationTr: '„Zusammen" derken iki gruptan tek büyük grup yaparsın.',
    },
  },
];
