import type { Lesson } from '../../types/content';

/**
 * US pack, modules A and B.
 * Same engine, same skills — American classroom wording and contexts.
 * Numbers stay within 20.
 */
export const usModuleAB: Lesson[] = [
  {
    id: 'ua1',
    moduleId: 'A',
    skillId: 'us-instruction-circle',
    title: 'Circle all — I show every one',
    objective: 'I know that “circle all” means I show every thing that fits, not just one.',
    story: 'Math papers often say “Circle all …”. That means: show every thing that fits.',
    steps: [
      {
        id: 'ua1-s1',
        interactionType: 'select-multiple',
        instruction: 'Circle all the apples.',
        items: [
          { id: 'ap1', label: 'apple', emoji: '🍎' },
          { id: 'pe1', label: 'pear', emoji: '🍐' },
          { id: 'ap2', label: 'apple', emoji: '🍎' },
          { id: 'ba1', label: 'banana', emoji: '🍌' },
          { id: 'ap3', label: 'apple', emoji: '🍎' },
        ],
        correctAnswer: ['ap1', 'ap2', 'ap3'],
        hint: 'There is more than one apple. Look at each picture by itself.',
        hintDetail: 'Go from left to right. Ask yourself about every picture: is this an apple? If yes, tap it.',
        explanation: 'There are 3 apples. With “circle all” you always show every thing that fits.',
      },
      {
        id: 'ua1-s2',
        interactionType: 'select-multiple',
        instruction: 'Circle all the numbers that are less than 10.',
        items: [
          { id: 'n5', label: '5' },
          { id: 'n14', label: '14' },
          { id: 'n8', label: '8' },
          { id: 'n17', label: '17' },
          { id: 'n3', label: '3' },
        ],
        correctAnswer: ['n5', 'n8', 'n3'],
        hint: 'Less than 10 means the number comes before 10 when you count.',
        hintDetail: 'Count: 1, 2, 3 … 9, 10. Everything before 10 is less than 10. 14 and 17 come later.',
        explanation: '5, 8 and 3 come before 10 when counting, so they are less than 10.',
      },
      {
        id: 'ua1-s3',
        interactionType: 'select-one',
        instruction: 'What does “Circle all the squares” mean?',
        items: [
          { id: 'o1', label: 'I show every square.' },
          { id: 'o2', label: 'I show only one square.' },
          { id: 'o3', label: 'I color the whole page.' },
        ],
        correctAnswer: 'o1',
        hint: 'Think about the word “all”.',
        hintDetail: '“All” means no square gets left out. So you show every single square.',
        explanation: '“Circle all” means: I show every thing that fits.',
      },
    ],
    transferTask: {
      id: 'ua1-t',
      interactionType: 'select-multiple',
      instruction: 'Circle all the animals with four legs.',
      items: [
        { id: 'dog', label: 'dog', emoji: '🐶' },
        { id: 'bird', label: 'bird', emoji: '🐦' },
        { id: 'cat', label: 'cat', emoji: '🐱' },
        { id: 'fish', label: 'fish', emoji: '🐟' },
        { id: 'horse', label: 'horse', emoji: '🐴' },
      ],
      correctAnswer: ['dog', 'cat', 'horse'],
      hint: 'Count the legs on each animal.',
      hintDetail: 'A bird has two legs. A fish has none. Dog, cat and horse walk on four legs.',
      explanation: 'Dog, cat and horse have four legs. That makes 3 animals.',
    },
  },

  {
    id: 'ua2',
    moduleId: 'A',
    skillId: 'us-instruction-choose',
    title: 'Choose — I pick exactly one',
    objective: 'I know that “choose” means I decide on exactly one answer.',
    story: 'Sometimes the paper says “Choose the …”. Then you look for exactly one thing that fits.',
    steps: [
      {
        id: 'ua2-s1',
        interactionType: 'select-one',
        instruction: 'Choose the picture that shows exactly 6 stars.',
        items: [
          { id: 'v5', label: '5 stars', emoji: '⭐⭐⭐⭐⭐' },
          { id: 'v6', label: '6 stars', emoji: '⭐⭐⭐⭐⭐⭐' },
          { id: 'v7', label: '7 stars', emoji: '⭐⭐⭐⭐⭐⭐⭐' },
        ],
        correctAnswer: 'v6',
        hint: 'Count the stars in each row with your finger.',
        hintDetail: 'Touch every star once and count out loud: 1, 2, 3, 4, 5, 6. Only one row stops at 6.',
        explanation: 'The middle row has 6 stars. With “choose” you pick exactly one answer.',
      },
      {
        id: 'ua2-s2',
        interactionType: 'select-one',
        instruction: 'Choose the sentence that matches the picture.',
        context: 'There are cats and dogs in the yard.',
        sceneGroups: [
          { label: 'cats', emoji: '🐱', count: 4 },
          { label: 'dogs', emoji: '🐶', count: 2 },
        ],
        items: [
          { id: 's1', label: 'There are 4 cats and 2 dogs.' },
          { id: 's2', label: 'There are 2 cats and 4 dogs.' },
          { id: 's3', label: 'There are 6 dogs.' },
        ],
        correctAnswer: 's1',
        hint: 'Count the cats first, then the dogs.',
        hintDetail: 'The cats are on top: 1, 2, 3, 4. The dogs are below: 1, 2. Find the sentence with those numbers.',
        explanation: '4 cats and 2 dogs. The sentence has to match the numbers you counted.',
      },
      {
        id: 'ua2-s3',
        interactionType: 'select-one',
        instruction: 'Choose the question you can answer with a number.',
        items: [
          { id: 'f1', label: 'How many kids are on the bus?' },
          { id: 'f2', label: 'Do you like soccer?' },
          { id: 'f3', label: 'What is your friend’s name?' },
        ],
        correctAnswer: 'f1',
        hint: 'Which question do you answer with “3” or “7”?',
        hintDetail: '“Do you like …?” is answered with yes or no. “What is your name?” is answered with a name. Only “How many …?” asks for an amount.',
        explanation: '“How many …?” asks for an amount, so you answer it with a number.',
      },
    ],
    transferTask: {
      id: 'ua2-t',
      interactionType: 'select-one',
      instruction: 'The paper says: “Choose a number that is greater than 7.” Which number fits?',
      items: [
        { id: 'z4', label: '4' },
        { id: 'z6', label: '6' },
        { id: 'z9', label: '9' },
      ],
      correctAnswer: 'z9',
      hint: 'Greater than 7 means the number comes after 7 when you count.',
      hintDetail: 'Count on from 7: 8, 9, 10. Those are greater than 7. 4 and 6 come earlier.',
      explanation: '9 comes after 7 when counting, so 9 is greater than 7.',
    },
  },

  {
    id: 'ua3',
    moduleId: 'A',
    skillId: 'us-instruction-sort',
    title: 'Sort — what belongs where?',
    objective: 'I know that “sort” means I put each thing in the place where it belongs.',
    story: 'When you sort, there are places and there are things. Every thing belongs in exactly one place.',
    steps: [
      {
        id: 'ua3-s1',
        interactionType: 'sort-groups',
        instruction: 'Sort them: fruit or vehicle?',
        targets: [
          { id: 'fruit', label: 'Fruit' },
          { id: 'vehicle', label: 'Vehicle' },
        ],
        items: [
          { id: 'i-apple', label: 'apple', emoji: '🍎' },
          { id: 'i-car', label: 'car', emoji: '🚗' },
          { id: 'i-banana', label: 'banana', emoji: '🍌' },
          { id: 'i-bus', label: 'bus', emoji: '🚌' },
          { id: 'i-cherry', label: 'cherry', emoji: '🍒' },
        ],
        correctAnswer: {
          'i-apple': 'fruit',
          'i-car': 'vehicle',
          'i-banana': 'fruit',
          'i-bus': 'vehicle',
          'i-cherry': 'fruit',
        },
        hint: 'Ask yourself: can you eat it, or can you ride in it?',
        hintDetail: 'Apple, banana and cherry can be eaten – that is fruit. A car and a bus take you places – those are vehicles.',
        explanation: 'Every picture has exactly one right place. That is what sorting means.',
      },
      {
        id: 'ua3-s2',
        interactionType: 'sort-groups',
        instruction: 'Sort the numbers.',
        targets: [
          { id: 'small', label: 'less than 10' },
          { id: 'big', label: 'greater than 10' },
        ],
        items: [
          { id: 'q6', label: '6' },
          { id: 'q15', label: '15' },
          { id: 'q9', label: '9' },
          { id: 'q18', label: '18' },
        ],
        correctAnswer: { q6: 'small', q15: 'big', q9: 'small', q18: 'big' },
        hint: 'Think of the number line: what comes before 10, what comes after?',
        hintDetail: '1 through 9 come before 10 – they are less. 11, 12, 13 … come after – they are greater.',
        explanation: '6 and 9 come before 10. 15 and 18 come after 10.',
      },
      {
        id: 'ua3-s3',
        interactionType: 'select-one',
        instruction: 'What does “sort” mean?',
        items: [
          { id: 'z1', label: 'I put each thing where it belongs.' },
          { id: 'z2', label: 'I count everything together.' },
          { id: 'z3', label: 'I look for the biggest thing.' },
        ],
        correctAnswer: 'z1',
        hint: 'When you sort, nothing is left over.',
        hintDetail: 'Sorting means putting things in groups. Every thing gets a place. You do not do any math.',
        explanation: '“Sort” means grouping: every thing goes where it belongs.',
      },
    ],
    transferTask: {
      id: 'ua3-t',
      interactionType: 'sort-groups',
      instruction: 'Sort them: animal or tool?',
      targets: [
        { id: 'animal', label: 'Animal' },
        { id: 'tool', label: 'Tool' },
      ],
      items: [
        { id: 't-dog', label: 'dog', emoji: '🐶' },
        { id: 't-hammer', label: 'hammer', emoji: '🔨' },
        { id: 't-cat', label: 'cat', emoji: '🐱' },
        { id: 't-wrench', label: 'wrench', emoji: '🔧' },
      ],
      correctAnswer: { 't-dog': 'animal', 't-hammer': 'tool', 't-cat': 'animal', 't-wrench': 'tool' },
      hint: 'Is it alive, or do you work with it?',
      hintDetail: 'An animal is alive and moves by itself. A tool is something you pick up to build or fix something.',
      explanation: 'Dog and cat are animals. Hammer and wrench are tools.',
    },
  },

  {
    id: 'ub1',
    moduleId: 'B',
    skillId: 'us-join',
    title: 'Something is added',
    objective: 'I see in the story that a group gets bigger, and I find the matching number sentence.',
    story: 'There are 6 cookies on the plate. Dad puts 4 more cookies on it.',
    steps: [
      {
        id: 'ub1-s1',
        interactionType: 'move-objects',
        instruction: 'Put 4 more cookies on the plate.',
        context: 'There are 6 cookies on the plate. Dad puts 4 more cookies on it.',
        mode: 'add',
        emoji: '🍪',
        objectLabel: 'cookie',
        startCount: 6,
        moveCount: 4,
        sourceLabel: 'Dad’s tray',
        targetLabel: 'Plate',
        correctAnswer: 4,
        hint: 'Dad adds 4 cookies. Move exactly 4 cookies to the plate.',
        hintDetail: 'Tap one cookie on Dad’s tray. It moves to the plate. Do that four times.',
        explanation: 'The 4 cookies join the 6 cookies. The amount on the plate gets bigger.',
      },
      {
        id: 'ub1-s2',
        interactionType: 'select-one',
        instruction: 'Which number sentence matches the story?',
        context: 'There are 6 cookies on the plate. Dad puts 4 more cookies on it.',
        items: [
          { id: 'r1', label: '6 + 4' },
          { id: 'r2', label: '6 − 4' },
          { id: 'r3', label: '4 − 6' },
        ],
        correctAnswer: 'r1',
        hint: 'There are more cookies on the plate now than before.',
        hintDetail: 'It started with 6 cookies and 4 came to join them. When a group gets bigger, you put the groups together: 6 + 4.',
        explanation: 'Two groups are joined: 6 cookies and 4 cookies. That is why it is 6 + 4.',
      },
      {
        id: 'ub1-s3',
        interactionType: 'number-input',
        instruction: 'How many cookies are on the plate now?',
        context: 'There are 6 cookies on the plate. Dad puts 4 more cookies on it.',
        unit: 'cookies',
        correctAnswer: 10,
        hint: 'Count on from 6: 7, 8 …',
        hintDetail: 'Start at 6 and count the 4 new cookies one by one: 7, 8, 9, 10. Stop at 10.',
        explanation: '6 + 4 = 10. There are 10 cookies on the plate now.',
      },
    ],
    transferTask: {
      id: 'ub1-t',
      interactionType: 'number-input',
      instruction: 'How many kids are on the bus now?',
      context: 'There are 8 kids on the bus. At the stop, 5 more kids get on.',
      unit: 'kids',
      correctAnswer: 13,
      hint: 'When kids get on, does the group get bigger or smaller?',
      hintDetail: 'Getting on means those kids are on the bus too now. The group gets bigger. Work out 8 + 5.',
      explanation: '8 + 5 = 13. Because kids get on, the group on the bus gets bigger.',
    },
  },

  {
    id: 'ub2',
    moduleId: 'B',
    skillId: 'us-separate',
    title: 'Something is taken away',
    objective: 'I see in the story that a group gets smaller, and I find the matching number sentence.',
    story: 'Mia has 9 marbles. She gives Ben 4 marbles.',
    steps: [
      {
        id: 'ub2-s1',
        interactionType: 'select-one',
        instruction: 'What do you need to find out?',
        context: 'Mia has 9 marbles. She gives Ben 4 marbles. How many marbles does Mia have left?',
        items: [
          { id: 'w1', label: 'How many marbles Mia has left.' },
          { id: 'w2', label: 'How many marbles Ben had before.' },
          { id: 'w3', label: 'How many marbles make 10 together.' },
        ],
        correctAnswer: 'w1',
        hint: 'Read the question at the end of the story one more time.',
        hintDetail: 'The question is “How many marbles does Mia have left?” So you are looking for Mia’s amount after she gives some away.',
        explanation: 'You are looking for what Mia has left. Knowing the question first makes the math easier.',
      },
      {
        id: 'ub2-s2',
        interactionType: 'move-objects',
        instruction: 'Give Ben 4 marbles.',
        context: 'Mia has 9 marbles. She gives Ben 4 marbles.',
        mode: 'remove',
        emoji: '🔵',
        objectLabel: 'marble',
        startCount: 9,
        moveCount: 4,
        sourceLabel: 'Mia',
        targetLabel: 'Ben',
        correctAnswer: 4,
        hint: 'Move exactly 4 marbles from Mia to Ben.',
        hintDetail: 'Tap one of Mia’s marbles and it moves over to Ben. Do that four times. The rest stays with Mia.',
        explanation: '4 of Mia’s 9 marbles go away. Her amount gets smaller.',
      },
      {
        id: 'ub2-s3',
        interactionType: 'number-input',
        instruction: 'How many marbles does Mia have left?',
        context: 'Mia has 9 marbles. She gives Ben 4 marbles.',
        unit: 'marbles',
        correctAnswer: 5,
        hint: 'Count backwards from 9: 8, 7 …',
        hintDetail: 'Take the 4 marbles away one at a time: 9 → 8 → 7 → 6 → 5. Mia has 5 marbles left.',
        explanation: '9 − 4 = 5. Mia keeps 5 marbles.',
      },
    ],
    transferTask: {
      id: 'ub2-t',
      interactionType: 'number-input',
      instruction: 'How many grapes are left on the plate?',
      context: 'There are 13 grapes on the plate. Lea eats 5 grapes.',
      unit: 'grapes',
      correctAnswer: 8,
      hint: 'Grapes that have been eaten are not on the plate anymore.',
      hintDetail: '5 of the 13 grapes go away. Count backwards: 12, 11, 10, 9, 8. Or work out 13 − 5.',
      explanation: '13 − 5 = 8. Because Lea eats grapes, the amount on the plate gets smaller.',
    },
  },

  {
    id: 'ub3',
    moduleId: 'B',
    skillId: 'us-join-or-separate',
    title: 'Does it get bigger or smaller?',
    objective: 'I use the story to decide whether an amount gets bigger or smaller.',
    story: 'The single word does not decide it. What happens in the story does.',
    steps: [
      {
        id: 'ub3-s1',
        interactionType: 'select-one',
        instruction: 'Does it get bigger or smaller?',
        context: 'Tom has 7 stickers. Lisa gives him 6 stickers.',
        items: [
          { id: 'm1', label: 'Tom has more stickers now.' },
          { id: 'm2', label: 'Tom has fewer stickers now.' },
          { id: 'm3', label: 'Tom has the same number of stickers.' },
        ],
        correctAnswer: 'm1',
        hint: 'Tom is given something. What happens to his pile?',
        hintDetail: 'Giving means Lisa hands them over and Tom receives them. So Tom’s pile grows.',
        explanation: 'Tom gets more stickers. His amount gets bigger.',
      },
      {
        id: 'ub3-s2',
        interactionType: 'select-one',
        instruction: 'Which number sentence matches?',
        context: 'Sara has 15 cards. She gives away 6 cards.',
        items: [
          { id: 'k1', label: '15 − 6' },
          { id: 'k2', label: '15 + 6' },
          { id: 'k3', label: '6 + 6' },
        ],
        correctAnswer: 'k1',
        hint: 'Sara gives cards away. Does she have more or fewer afterwards?',
        hintDetail: 'Giving away means the cards are gone. Sara’s amount gets smaller, so it is 15 − 6.',
        explanation: '6 of Sara’s 15 cards go away: 15 − 6.',
      },
      {
        id: 'ub3-s3',
        interactionType: 'number-input',
        instruction: 'How many cards does Sara have left?',
        context: 'Sara has 15 cards. She gives away 6 cards.',
        unit: 'cards',
        correctAnswer: 9,
        hint: 'Count backwards from 15.',
        hintDetail: 'Take the 6 cards away one at a time: 14, 13, 12, 11, 10, 9. She has 9 cards left.',
        explanation: '15 − 6 = 9. Sara keeps 9 cards.',
      },
    ],
    transferTask: {
      id: 'ub3-t',
      interactionType: 'number-input',
      instruction: 'How many apples are left in the basket?',
      context: 'There are 16 apples in the basket. Grandma takes out 7 apples.',
      unit: 'apples',
      correctAnswer: 9,
      hint: 'Taking out means the apples are not in the basket anymore.',
      hintDetail: 'The basket has 16 apples and 7 come out. The amount in the basket gets smaller: 16 − 7.',
      explanation: '16 − 7 = 9. There are 9 apples left in the basket.',
    },
  },
];
