import type { Lesson } from '../../types/content';

/** US pack, modules C and D. Comparing amounts and reading the question. */
export const usModuleCD: Lesson[] = [
  {
    id: 'uc1',
    moduleId: 'C',
    skillId: 'us-compare',
    title: 'More, fewer or the same?',
    objective: 'I compare two groups and say which one has more, fewer or the same amount.',
    story: 'When you compare, you line up two groups and look at which line is longer.',
    steps: [
      {
        id: 'uc1-s1',
        interactionType: 'select-one',
        instruction: 'Which group has more?',
        sceneGroups: [
          { label: 'fish', emoji: '🐟', count: 7 },
          { label: 'turtles', emoji: '🐢', count: 4 },
        ],
        items: [
          { id: 'g1', label: 'There are more fish.' },
          { id: 'g2', label: 'There are more turtles.' },
          { id: 'g3', label: 'There is the same amount.' },
        ],
        correctAnswer: 'g1',
        hint: 'Make pairs: one fish and one turtle. What is left over?',
        hintDetail: 'The rows are under each other. Count: 7 fish, 4 turtles. The fish row is longer, so fish are left over.',
        explanation: '7 is greater than 4. After pairing, 3 fish are left over, so there are more fish.',
      },
      {
        id: 'uc1-s2',
        interactionType: 'select-one',
        instruction: 'How is it here?',
        sceneGroups: [
          { label: 'stars', emoji: '⭐', count: 6 },
          { label: 'hearts', emoji: '❤️', count: 6 },
        ],
        items: [
          { id: 'h1', label: 'There is the same amount.' },
          { id: 'h2', label: 'There are more stars.' },
          { id: 'h3', label: 'There are more hearts.' },
        ],
        correctAnswer: 'h1',
        hint: 'Does every star get exactly one heart?',
        hintDetail: 'Make pairs in your head: star–heart. If nothing is left over, the amounts are the same.',
        explanation: '6 and 6 are equal. Nothing is left over, so it is the same amount.',
      },
      {
        id: 'uc1-s3',
        interactionType: 'select-one',
        instruction: 'What does “fewer” mean?',
        items: [
          { id: 'w1', label: 'There are not as many.' },
          { id: 'w2', label: 'There are more.' },
          { id: 'w3', label: 'There is exactly the same amount.' },
        ],
        correctAnswer: 'w1',
        hint: 'Fewer is the opposite of more.',
        hintDetail: 'If one row is shorter than the other, there are fewer things in it – not as many.',
        explanation: '“Fewer” means: there are not as many of this thing as of the other one.',
      },
    ],
    transferTask: {
      id: 'uc1-t',
      interactionType: 'select-one',
      instruction: 'Which group has fewer?',
      sceneGroups: [
        { label: 'apples', emoji: '🍎', count: 9 },
        { label: 'pears', emoji: '🍐', count: 12 },
      ],
      items: [
        { id: 'x1', label: 'There are fewer apples.' },
        { id: 'x2', label: 'There are fewer pears.' },
        { id: 'x3', label: 'There is the same amount.' },
      ],
      correctAnswer: 'x1',
      hint: 'Which row is shorter?',
      hintDetail: 'Count both rows: 9 apples, 12 pears. The shorter row has fewer.',
      explanation: '9 is less than 12, so there are fewer apples.',
    },
  },

  {
    id: 'uc2',
    moduleId: 'C',
    skillId: 'us-difference',
    title: 'How many more?',
    objective: 'I understand that “how many more” asks for the difference between two groups.',
    story: 'Lena has 11 stickers. Ben has 7 stickers.',
    steps: [
      {
        id: 'uc2-s1',
        interactionType: 'select-one',
        instruction: 'What do you need to find out?',
        context: 'Lena has 11 stickers. Ben has 7 stickers. How many more stickers does Lena have than Ben?',
        sceneGroups: [
          { label: 'Lena', emoji: '🌟', count: 11 },
          { label: 'Ben', emoji: '🌟', count: 7 },
        ],
        items: [
          { id: 'u1', label: 'The difference between 11 and 7.' },
          { id: 'u2', label: 'How many stickers they have altogether.' },
          { id: 'u3', label: 'How many stickers Ben wants to buy.' },
        ],
        correctAnswer: 'u1',
        hint: 'The question compares Lena and Ben.',
        hintDetail: 'Make pairs: every sticker of Ben’s goes with one of Lena’s. The question asks how many are left over on Lena’s side – that is the difference.',
        explanation: '“How many more?” asks for the difference, not for the total.',
      },
      {
        id: 'uc2-s2',
        interactionType: 'select-one',
        instruction: 'Which number sentence matches?',
        context: 'Lena has 11 stickers. Ben has 7 stickers.',
        items: [
          { id: 'v1', label: '11 − 7' },
          { id: 'v2', label: '11 + 7' },
          { id: 'v3', label: '7 + 7' },
        ],
        correctAnswer: 'v1',
        hint: 'You are looking for what is left over on Lena’s side.',
        hintDetail: 'Take as many away from Lena’s 11 as Ben has (7). What is left over is the difference: 11 − 7.',
        explanation: 'You find the difference by taking the smaller amount away from the bigger one: 11 − 7.',
      },
      {
        id: 'uc2-s3',
        interactionType: 'number-input',
        instruction: 'How many more stickers does Lena have than Ben?',
        context: 'Lena has 11 stickers. Ben has 7 stickers.',
        unit: 'stickers',
        correctAnswer: 4,
        hint: 'Count on from 7 to 11. How many steps is that?',
        hintDetail: 'From 7 to 11: 8 (1 step), 9 (2 steps), 10 (3 steps), 11 (4 steps). The difference is 4.',
        explanation: '11 − 7 = 4. Lena has 4 more stickers than Ben.',
      },
    ],
    transferTask: {
      id: 'uc2-t',
      interactionType: 'number-input',
      instruction: 'How many more birds are in the tree than on the fence?',
      context: 'There are 14 birds in the tree. There are 8 birds on the fence.',
      unit: 'birds',
      correctAnswer: 6,
      hint: 'Compare the two groups.',
      hintDetail: 'Every bird on the fence goes with one in the tree. The extra birds in the tree are left over: 14 − 8.',
      explanation: '14 − 8 = 6. There are 6 more birds in the tree.',
    },
  },

  {
    id: 'uc3',
    moduleId: 'C',
    skillId: 'us-make-equal',
    title: 'Making them equal',
    objective: 'I find out how many are missing so that two groups are the same size.',
    story: 'Mia has 12 blocks. Tim has 8 blocks. They both want the same number.',
    steps: [
      {
        id: 'uc3-s1',
        interactionType: 'select-one',
        instruction: 'How do you find out how many blocks Tim still needs?',
        context: 'Mia has 12 blocks. Tim has 8 blocks.',
        sceneGroups: [
          { label: 'Mia', emoji: '🟦', count: 12 },
          { label: 'Tim', emoji: '🟦', count: 8 },
        ],
        items: [
          { id: 'a1', label: 'I look for the difference between 12 and 8.' },
          { id: 'a2', label: 'I work out 12 + 8.' },
          { id: 'a3', label: 'I count all the blocks together.' },
        ],
        correctAnswer: 'a1',
        hint: 'Tim’s row is shorter. How much is missing to reach Mia’s row?',
        hintDetail: 'Put both rows under each other. The empty space at the end of Tim’s row shows how many are missing. That is the difference.',
        explanation: 'The missing amount is the difference between the two groups.',
      },
      {
        id: 'uc3-s2',
        interactionType: 'number-input',
        instruction: 'How many blocks does Tim still need?',
        context: 'Mia has 12 blocks. Tim has 8 blocks.',
        unit: 'blocks',
        correctAnswer: 4,
        hint: 'Count on from 8 to 12.',
        hintDetail: 'From 8 to 12: 9, 10, 11, 12. That is 4 steps. Tim needs 4 blocks.',
        explanation: '12 − 8 = 4. With 4 more blocks Tim has just as many as Mia.',
      },
      {
        id: 'uc3-s3',
        interactionType: 'select-one',
        instruction: 'How many blocks does each child have then?',
        context: 'Tim was given 4 more blocks.',
        items: [
          { id: 'e1', label: 'Each child has 12 blocks.' },
          { id: 'e2', label: 'Each child has 20 blocks.' },
          { id: 'e3', label: 'Each child has 8 blocks.' },
        ],
        correctAnswer: 'e1',
        hint: 'Mia’s amount did not change.',
        hintDetail: 'Mia had 12 and gave nothing away. Tim had 8 and got 4 more: 8 + 4 = 12. Both have 12.',
        explanation: 'Tim: 8 + 4 = 12. Mia still has 12. Now they are equal.',
      },
    ],
    transferTask: {
      id: 'uc3-t',
      interactionType: 'number-input',
      instruction: 'How many more chairs are needed in row B so both rows have the same number?',
      context: 'Row A has 15 chairs. Row B has 9 chairs.',
      unit: 'chairs',
      correctAnswer: 6,
      hint: 'How far is it from 9 to 15?',
      hintDetail: 'Count on from 9: 10, 11, 12, 13, 14, 15. That is 6 steps. Or work out 15 − 9.',
      explanation: '15 − 9 = 6. With 6 more chairs both rows have 15 chairs.',
    },
  },

  {
    id: 'ud1',
    moduleId: 'D',
    skillId: 'us-find-question',
    title: 'What is the question asking?',
    objective: 'I read the question carefully and say which information is being asked for.',
    story: 'Paul collects rocks. On Monday he finds 8 rocks. On Tuesday he finds 6 rocks.',
    steps: [
      {
        id: 'ud1-s1',
        interactionType: 'select-one',
        instruction: 'The question is: “How many rocks does Paul have altogether?” What do you need to find out?',
        context: 'Paul finds 8 rocks on Monday and 6 rocks on Tuesday.',
        items: [
          { id: 'f1', label: 'The number of all the rocks from both days.' },
          { id: 'f2', label: 'How many rocks he found on Monday only.' },
          { id: 'f3', label: 'Which day he found more.' },
        ],
        correctAnswer: 'f1',
        hint: 'Watch out for the word “altogether”.',
        hintDetail: '“Altogether” means both days in one amount. You put Monday’s and Tuesday’s rocks into one pile.',
        explanation: 'What is asked for is the total from both days.',
      },
      {
        id: 'ud1-s2',
        interactionType: 'number-input',
        instruction: 'How many rocks does Paul have altogether?',
        context: 'Monday: 8 rocks. Tuesday: 6 rocks.',
        unit: 'rocks',
        correctAnswer: 14,
        hint: 'Put both amounts together.',
        hintDetail: 'Start at 8 and count on Tuesday’s 6 rocks: 9, 10, 11, 12, 13, 14.',
        explanation: '8 + 6 = 14. Both piles together are 14 rocks.',
      },
      {
        id: 'ud1-s3',
        interactionType: 'select-one',
        instruction: 'Now the question is: “On which day did Paul find more rocks?” What is the answer?',
        context: 'Monday: 8 rocks. Tuesday: 6 rocks.',
        sceneGroups: [
          { label: 'Monday', emoji: '🪨', count: 8 },
          { label: 'Tuesday', emoji: '🪨', count: 6 },
        ],
        items: [
          { id: 'g1', label: 'On Monday.' },
          { id: 'g2', label: 'On Tuesday.' },
          { id: 'g3', label: 'The same on both days.' },
        ],
        correctAnswer: 'g1',
        hint: 'This question does not want a total, it wants a comparison.',
        hintDetail: 'Compare 8 and 6. The bigger number belongs to the day with more rocks.',
        explanation: '8 is greater than 6. The same story can have different questions.',
      },
    ],
    transferTask: {
      id: 'ud1-t',
      interactionType: 'select-one',
      instruction: 'What do you need to find out?',
      context: 'Nina has 11 balloons. 4 balloons pop. Question: How many balloons does Nina have left?',
      items: [
        { id: 'h1', label: 'How many balloons are left.' },
        { id: 'h2', label: 'How many balloons popped.' },
        { id: 'h3', label: 'How many balloons Nina bought.' },
      ],
      correctAnswer: 'h1',
      hint: 'Watch out for the word “left”.',
      hintDetail: '“Left” asks about the rest: what is still there at the end? The number 4 is already in the story.',
      explanation: 'What is asked for is the rest after they pop, not a number that is already given.',
    },
  },

  {
    id: 'ud2',
    moduleId: 'D',
    skillId: 'us-needed-numbers',
    title: 'Which numbers do I need?',
    objective: 'I see which numbers belong to the question and which ones I do not need.',
    story: 'Word problems sometimes have numbers you do not need for the math at all.',
    steps: [
      {
        id: 'ud2-s1',
        interactionType: 'select-multiple',
        instruction: 'Circle the numbers you need for the math.',
        context: 'Lisa is 8 years old. She has 7 books. She buys 5 more books. Question: How many books does Lisa have now?',
        items: [
          { id: 'j8', label: '8 years old' },
          { id: 'b7', label: '7 books' },
          { id: 'b5', label: '5 books' },
        ],
        correctAnswer: ['b7', 'b5'],
        hint: 'The question is about books, not about age.',
        hintDetail: 'Read the question: “How many books does Lisa have now?” Only numbers that count books belong in the math. Her age does not change how many books she has.',
        explanation: 'Books are asked for, so you need 7 and 5. The 8 years are not part of the math.',
      },
      {
        id: 'ud2-s2',
        interactionType: 'number-input',
        instruction: 'How many books does Lisa have now?',
        context: 'Lisa has 7 books and buys 5 more books.',
        unit: 'books',
        correctAnswer: 12,
        hint: 'Count on from 7.',
        hintDetail: 'Start at 7 and count on 5: 8, 9, 10, 11, 12.',
        explanation: '7 + 5 = 12. Lisa has 12 books now.',
      },
    ],
    transferTask: {
      id: 'ud2-t',
      interactionType: 'select-multiple',
      instruction: 'Circle the numbers you need for the math.',
      context: 'Tom invited 5 friends. He is 9 years old. There are 16 muffins on the table. The kids eat 7 muffins. Question: How many muffins are left on the table?',
      items: [
        { id: 'z5', label: '5 friends' },
        { id: 'z9', label: '9 years old' },
        { id: 'z16', label: '16 muffins' },
        { id: 'z7', label: '7 muffins' },
      ],
      correctAnswer: ['z16', 'z7'],
      hint: 'What is the problem asking about – muffins or kids?',
      hintDetail: 'It asks about muffins on the table. Only numbers that count muffins belong in the math: 16 and 7.',
      explanation: '16 and 7 belong in the math. Friends and age do not change the number of muffins.',
    },
  },

  {
    id: 'ud3',
    moduleId: 'D',
    skillId: 'us-choose-model',
    title: 'Which picture matches the question?',
    objective: 'I choose the right picture model: joining, taking away or comparing.',
    story: 'Every question matches one picture: joining, taking away, or comparing two groups.',
    steps: [
      {
        id: 'ud3-s1',
        interactionType: 'select-one',
        instruction: 'Which picture matches the question?',
        context: 'Anna has 6 pencils. She gets 5 more pencils. How many does she have now?',
        items: [
          { id: 'm1', label: 'Two groups are put together.', emoji: '🟢🟢🟢 ➕ 🟢🟢' },
          { id: 'm2', label: 'Something is taken away from one group.', emoji: '🟢🟢🟢 ➖' },
          { id: 'm3', label: 'Two groups are lined up and compared.', emoji: '🟢🟢🟢 ↔ 🔵🔵' },
        ],
        correctAnswer: 'm1',
        hint: 'Anna gets more pencils. Does her amount grow or shrink?',
        hintDetail: 'Getting more means a second group joins the first one. Both together make the new amount.',
        explanation: 'When something is added, you put two groups together.',
      },
      {
        id: 'ud3-s2',
        interactionType: 'select-one',
        instruction: 'Which picture matches the question?',
        context: 'Class A has 16 kids and class B has 12 kids. How many more kids are in class A?',
        items: [
          { id: 'n1', label: 'Two groups are lined up and compared.', emoji: '🟦🟦🟦 ↔ 🟧🟧' },
          { id: 'n2', label: 'Two groups are put together.', emoji: '🟦🟦🟦 ➕ 🟧🟧' },
          { id: 'n3', label: 'Something is taken away from one group.', emoji: '🟦🟦🟦 ➖' },
        ],
        correctAnswer: 'n1',
        hint: '“How many more” asks for the difference.',
        hintDetail: 'No kid leaves and no kid joins. Both classes stay. You line the rows up and see what is left over.',
        explanation: 'When comparing, both groups stay. What is asked for is the difference.',
      },
      {
        id: 'ud3-s3',
        interactionType: 'select-one',
        instruction: 'Which picture matches the question?',
        context: 'Ben eats 6 of the 14 cookies. How many are left?',
        items: [
          { id: 'o1', label: 'Something is taken away from one group.', emoji: '🍪🍪🍪🍪 ➖ 🍪🍪' },
          { id: 'o2', label: 'Two groups are put together.', emoji: '🍪🍪 ➕ 🍪🍪' },
          { id: 'o3', label: 'Two groups are lined up and compared.', emoji: '🍪🍪🍪 ↔ 🍪' },
        ],
        correctAnswer: 'o1',
        hint: 'Cookies that have been eaten are gone.',
        hintDetail: 'There is only one group: the 14 cookies. 6 of them disappear. The group gets smaller.',
        explanation: 'When taking away, a rest of one single group is left.',
      },
    ],
    transferTask: {
      id: 'ud3-t',
      interactionType: 'select-one',
      instruction: 'Which picture matches the question?',
      context: 'There are 8 red cups and 7 blue cups on the shelf. How many cups are there altogether?',
      items: [
        { id: 'p1', label: 'Two groups are put together.', emoji: '🔴🔴🔴 ➕ 🔵🔵🔵' },
        { id: 'p2', label: 'Something is taken away from one group.', emoji: '🔴🔴🔴 ➖' },
        { id: 'p3', label: 'Two groups are lined up and compared.', emoji: '🔴🔴🔴 ↔ 🔵🔵' },
      ],
      correctAnswer: 'p1',
      hint: 'Watch out for the word “altogether”.',
      hintDetail: 'The red and the blue cups are on the same shelf. For the total you put both groups together.',
      explanation: 'With “altogether” you make one big amount out of two groups.',
    },
  },
];
